### ISSUE TITLE
Unable to update thumbnail VTT while video source change

### ISSUE THREAD

**Issue by kfeng0806** [sampotts/plyr#1430] opened 2019-04-27 14:41 UTC
Hello,

How can i dynamic update thumbnail VTT source while changing player.source?
I can't update thumbnail VTT when video source updated.

![](https://i.imgur.com/WTwdW3l.jpg)

**Comment by kfeng0806** [comment] 2019-04-27 14:44
Maybe need a dynamic setter for thumbnails as well as poster?

**Comment by sampotts** [comment] 2019-04-27 14:46
Duplicate of https://github.com/sampotts/plyr/issues/1369

**Closed by sampotts** 2019-04-27 14:46 UTC
