### ISSUE TITLE
[V3] muted attribute is not working

### ISSUE THREAD

**Issue by thasmo** [sampotts/plyr#838] opened 2018-03-27 12:56 UTC
### Expected behaviour
`<video muted autoplay>` should play the video with muted audio.

### Actual behaviour
`plyr.js` does not respect the `muted` and does not mute the video.

### Environment
- Browser: Firefox 58
- Operating System: Ubuntu Linux
- Plyr: 3.0.3

**Comment by thasmo** [comment] 2018-03-27 13:27
Seems like even this does not work:
```js
new Plyr(element, {
    muted: true,
});
```

**Comment by sampotts** [comment] 2018-03-27 13:28
Sorry this must be a regression somewhere. Should be a quick fix.

**Comment by thasmo** [comment] 2018-03-27 13:36
On version `3.0.3` does this work for you?
```js
var api = new Plyr(element, {
    muted: true
});
api.pause();
```
The video does not pause for me.

**Comment by sampotts** [comment] 2018-03-27 13:37
Try this:

```javascript
var api = new Plyr(element, {
    muted: true
});
api.on('ready', () => { 
    api.pause();
});
```

**Comment by thetre97** [comment] 2018-04-02 22:24
I also can't get either the `muted: true` setup option to work, or  `player.muted = true` - this is with a Vimeo embed.

**Comment by sampotts** [comment] 2018-04-02 23:08
This should be fixed in the latest version 👍

**Closed by sampotts** 2018-04-02 23:08 UTC
Labels: Bug, Replicated

**Comment by xcrap** [comment] 2018-04-09 23:05
Not working in the latest version. 
Adding 
const player = new Plyr('#player', {muted:true, controls: ['play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen']}); or muted in the video, none of them mute the sound.

**Comment by sampotts** [comment] 2018-04-09 23:13
They won't if you've previously set the muted state and have it in local storage. Obviously the users settings overwrite the defaults. Try clearing your `plyr` local storage key.

**Comment by xcrap** [comment] 2018-04-09 23:16
Ups! Thank you.

**Comment by sampotts** [comment] 2018-04-09 23:16
Did that work? :)

**Comment by xcrap** [comment] 2018-04-10 02:17
I've also tested now in Firefox and it's ignoring everything.
Even with $("#video_loop").prop('muted', true); it makes nothing in firefox. Strange.

**Comment by janein** [comment] 2019-03-15 08:21
Still not working as expected.
But I got it working with the workaround on the 'ready' event.

**Comment by victor-gabou** [comment] 2019-11-05 14:22
From what I see, the problem is that Plyr keep informations in the localStorage. To reproduce the behavior.
On a webpage, init a plyr player with muted & autoplay
Load the page for the first time (sound is muted)
Activate the sound
Reload the page (sound isn't muted)

Is it the wanted behavior?

**Comment by kylescousin** [comment] 2020-01-18 16:15
Any news on this?

Once you unmute, everything is playing with sound after that

**Comment by mayeaux** [comment] 2020-08-25 03:35
Plyr is storing it in browser storage and its taking precedent over the muted attribute. Kind of a bad design because videos won't autoplay unless they're muted. Hard to say what the solution is, I'm just sick of being told 'oh you didn't interact with the DOM we can't start this video', weird.

**Comment by Jaikumar0101** [comment] 2021-11-07 11:48
hey I have resolved this issue with little simple steps

`const player = new Plyr('#player');
player.muted=true;
player.play();`
