### ISSUE TITLE
Toggle pause/play does not work on Android

### ISSUE THREAD

**Issue by omitech** [sampotts/plyr#718] opened 2017-11-20 11:10 UTC
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Click (or tap) on the video container (outside control buttons) should toggle pause/play.

### Actual behaviour
Pause does not work when clicking( or tapping) on the video container in Chrome on Widows with touchscreen monitor and in Chrome on Android (6/7). Video does start when clicking(tapping) on the video container, but does not pause. It only works on click(tap) on video control button. However, pause works in Chrome on non-touchscreen PC and it also works in IE edge, Firefox with / without touchscreen. 

So my guess, it is somehow related to handling touch events in Chrome. 

### Environment

- Browser: Chrome
- Version:  62.0.3202.94 (64-bit)
- Operating System: Windows 10
- Version: build 1709

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
- On an android device, start/pause video at https://plyr.io by tapping on the video container. It starts, but does not pause.

**Comment by jarekskuder** [comment] 2017-11-21 07:25
Same here. Everything was fine until recently. I have Cordova app that plays video stream and now every time I call pause, in the debugger I see pause event, but the video doesn't stop.

**Comment by omitech** [comment] 2017-11-21 12:49
I'm not seeing pause event triggered in Chrome (only when clicking pause button) :
v = document.getElementsByTagName("video")[0];
v.addEventListener("pause", function() {console.log('pause event')});

**Comment by omitech** [comment] 2017-11-22 07:56
I think the problem lies in this code https://github.com/sampotts/plyr/blob/9c4b53d761929ab7305f6bfdbd7fc541ed902d43/src/js/plyr.js#L3295
```
                // On click play, pause ore restart
                _on(wrapper, 'click', function() {
                    // Touch devices will just show controls (if we're hiding controls)
                    if (config.hideControls && plyr.browser.isTouch && !plyr.media.paused) {
                        return;
                    }
```
So basically if browser.isTouch == true then video will not pause on click (provided that hideControls is set to true). The problem is that  isTouch that is defined as  "ontouchstart" in document.documentElement returns true only in Chrome by default. 

IE, edge and firefox returns false even if touch events are supported by OS. In firefox you must explicitly set dom.w3c_touch_events.enabled to 1 (or 2) in config to enable touch events on desktop. 

Not sure if there are any workarounds for this. Maybe by defining separate touch and click events:  Click pauses the video, touch displays controls, and pauses if controls are already visible.

**Comment by sampotts** [comment] 2017-11-23 01:25
This is being fixed in v3 (working on it at the moment). It's one of the last big pieces of v3 work before it can be beta tested. The detection of touch devices has always been a bit flaky so I'm going to look at trying to listen for mouse vs touch events. The issue is iOS will sometimes fire `mousemove` even though it has no mouse, etc. It's a real pain.

**Comment by sampotts** [comment] 2018-03-21 14:20
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Closed by sampotts** 2018-03-21 14:20 UTC
Labels: Bug, Fixed in V3

**Comment by fietstouring** [comment] 2018-05-19 13:26
still seems to be an issue in latest version 3.3.7, at least for me.
Pause not possible on Android chrome

**Comment by friday** [comment] 2018-05-19 18:06
@fietstouring See #968

**Comment by ilearnio** [comment] 2019-01-07 08:55
Doesn't work for me as well. Since I am hiding all controls except big play button and fullscreen, there is no way to pause the video

**Comment by ilearnio** [comment] 2019-01-07 11:30
My temporary workaround, maybe it will save someone's time

```js
/**
 * Fixes pausing on click on mobile
 * https://github.com/sampotts/plyr/issues/718
 */
fixMobileClick () {
  const player = this.plyrVideo
  const { wrapper, container } = player.elements
  if (!container._clickListener) {
    container._clickListener = event => {
      const targets = [container, wrapper]

      // Ignore if click if not container or in video wrapper
      if (!targets.includes(event.target) && !wrapper.contains(event.target)) {
        return
      }

      if (player.touch) player.togglePlay()
    }
    container.addEventListener('click', container._clickListener)
  }
},
```

**Comment by patchon** [comment] 2019-06-24 17:33
> ```js
> fixMobileClick () {
>   const player = this.plyrVideo
>   const { wrapper, container } = player.elements
>   if (!container._clickListener) {
>     container._clickListener = event => {
>       const targets = [container, wrapper]
> 
>       // Ignore if click if not container or in video wrapper
>       if (!targets.includes(event.target) && !wrapper.contains(event.target)) {
>         return
>       }
> 
>       if (player.touch) player.togglePlay()
>     }
>     container.addEventListener('click', container._clickListener)
>   }
> },
> ```

Thanks for this!

**Comment by CiriousJoker** [comment] 2020-04-01 00:41
I couldn't get @ilearnio 's solution to work, so here's mine:

```
  /**
   * Fixes pausing on click on mobile
   * https://github.com/sampotts/plyr/issues/718
   */
  const videoWrapper = document.getElementsByClassName("plyr__video-wrapper")[0];
  videoWrapper.addEventListener("click", event => {
    player.togglePlay();
  });

  player.toggleControls(false);
```

Querying for .plyr__video-wrapper could fail for multi-video sites, keep that in mind!

**Comment by drzeitraum** [comment] 2020-09-27 01:06
In version 3.6.2 the problem still exists.
For multi-video:
```
const players = Array.from(document.querySelectorAll('<SELECTOR>')).map(player => new Plyr(player));
players.forEach(function (player, i) {
    document.getElementsByClassName("plyr__video-wrapper")[i].addEventListener("click", event => {
        player.togglePlay();
    });
});

```

**Comment by zdjzce923** [comment] 2022-09-08 15:07
> 我无法得到@ilearnio的工作解决方案，所以这是我的：
> 
> ```
>   /**
>    * Fixes pausing on click on mobile
>    * https://github.com/sampotts/plyr/issues/718
>    */
>   const videoWrapper = document.getElementsByClassName("plyr__video-wrapper")[0];
>   videoWrapper.addEventListener("click", event => {
>     player.togglePlay();
>     event.stopPropagation(); // Necessary or the video will toggle twice => no playback
>   });
> 
>   player.toggleControls(false);
> ```
> 
> 对于多视频网站，查询 .plyr__video-wrapper 可能会失败，请记住这一点！

awesome

**Comment by zdjzce923** [comment] 2022-09-08 15:10
> I couldn't get @ilearnio 's solution to work, so here's mine:
> 
> ```
>   /**
>    * Fixes pausing on click on mobile
>    * https://github.com/sampotts/plyr/issues/718
>    */
>   const videoWrapper = document.getElementsByClassName("plyr__video-wrapper")[0];
>   videoWrapper.addEventListener("click", event => {
>     player.togglePlay();
>     event.stopPropagation(); // Necessary or the video will toggle twice => no playback
>   });
> 
>   player.toggleControls(false);
> ```
> 
> Querying for .plyr__video-wrapper could fail for multi-video sites, keep that in mind!

thanks! this worked for me

**Comment by HeadStudios** [comment] 2023-02-21 02:24
> /**
>    * Fixes pausing on click on mobile
>    * https://github.com/sampotts/plyr/issues/718
>    */
>   const videoWrapper = document.getElementsByClassName("plyr__video-wrapper")[0];
>   videoWrapper.addEventListener("click", event => {
>     player.togglePlay();
>     event.stopPropagation(); // Necessary or the video will toggle twice => no playback
>   });
> 
>   player.toggleControls(false);

Thank you! This worked perfectly for me - surprised this hasn't been implemented in the main build

**Comment by HeadStudios** [comment] 2023-03-27 21:20
> Since 5 years, the problem still exists. Man!

Nah bro I figured it out and it was working for me there's a hack around it.

**Comment by kw005** [comment] 2023-03-27 21:24
Yeah, the hack is working here too, but still. It should have already implemented. Every new user will discover the same issue :(

**Comment by sampotts** [comment] 2023-03-27 23:24
> Since 5 years, the problem still exists. Man!

5 years and no one's opened a pull request?! Shocking! It's almost like you folks don't know what the _open_ in open source means, but sure, keep complaining about this _free_ product, that'll definitely get it sorted.

**Comment by sampotts** [comment] 2023-03-27 23:29
I, probably like yourself, have a full-time job, that isn't looking after Plyr or any other open-source projects. Having a family means I have even less time to work on this. If it really bothers you, you can just learn how to open a pull request.  

If I didn't get $6 a month in donations, I'd probably feel a bit more motivated to work on it. So many freeloaders in open source that only contribute complaints.  

Since a few folks have posted fixes further up, I'll take a look at adding that in.

**Comment by HeadStudios** [comment] 2023-03-27 23:50
> I, probably like yourself, have a full-time job, that isn't looking after Plyr or any other open-source projects. Having a family means I have even less time to work on this. If it really bothers you, you can just learn how to open a pull request.
> 
> If I didn't get $6 a month in donations, I'd probably feel a bit more motivated to work on it. So many freeloaders in open source that only contribute complaints.
> 
> Since a few folks have posted fixes further up, I'll take a look at adding that in.

Hey Sam I just wanted to say I really appreciate your work and am using the Plyr player, people like myself and many others are really grateful for the contributions you make. Peace brother. I'm just happy there's a community here and hey if the hack works I'm happy.

**Comment by rodrigobg** [comment] 2023-07-07 16:27
> Eu, provavelmente como você, tenho um emprego em tempo integral, que não é cuidar do Plyr ou de qualquer outro projeto de código aberto. Ter uma família significa que tenho ainda menos tempo para trabalhar nisso. Se isso realmente te incomoda, você pode simplesmente aprender como abrir uma pull request.
> 
> Se eu não recebesse $ 6 por mês em doações, provavelmente me sentiria um pouco mais motivado para trabalhar nisso. Tantos aproveitadores em código aberto que só contribuem com reclamações.
> 
> Como algumas pessoas postaram correções mais adiante, darei uma olhada em adicioná-las.

Hello Sam, I hope this hack helps to solve the problem once and for all!!! And thank you for this wonderful video player that you have created.

Segue o hack: 
Crie uma div com esta classe: "player_um"
Envolva seu Plyr dentro dessa div. 
Crie um const no javascript: 
`const playerDiv = document.querySelector('.player_um');`

Agora vamos ouvir o evento da div: "player_um"
`//Tentando corrigir o problema do pause no touch.
playerDiv.addEventListener('click', function() {
  if (player.playing) {
    player.pause();
  } else {
    player.play();
  }
});
//Tentando corrigir o problema do pause no touch.`

Eu duvido que isso não funcione. E sim, estou escrevendo em Português do Brasil, vocês que se virem pra traduzir a minha língua. Seus preguiçosos. 

Example working here: https://www.playermoney.com.br
