### ISSUE TITLE
Removing Unused Parts For Build

### ISSUE THREAD

**Issue by amir-mln** [sampotts/plyr#2264] opened 2021-07-04 07:21 UTC
### Expected behaviour
Being capable of removing this unused parts such as plugins.js, captions.js with tree-shaking/cherry-picking

![](https://user-images.githubusercontent.com/69141584/121321676-9376b200-c923-11eb-8db0-3da153e1bd05.png)

### Actual behaviour
Everything gets bundled (smh)

### Steps to reproduce
`npm run build` and the analyze the bundle

**Comment by sampotts** [comment] 2021-07-04 08:26
Duplicate of #2239 (smh)

**Closed by sampotts** 2021-07-04 08:26 UTC
