### ISSUE TITLE
Setup issue: SVG sprite buttons not display in Firefox

### ISSUE THREAD

**Issue by buszmen201** [sampotts/plyr#927] opened 2018-04-28 20:24 UTC
### Expected behaviour
Like in Edge:
![image](https://user-images.githubusercontent.com/29873044/39400297-5a7b5a6c-4b2e-11e8-988e-1ab10d4c99be.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/29873044/39400315-874113a2-4b2e-11e8-8334-f99859df2309.png)

### Environment

- Browser: Firefox
- Version: 60.0b16 (64 bit)
- Operating System: MS Windows 10 x64
- Version: 1709 (16299.371)

### Steps to reproduce
File is builded using Python with module yattag
scripts: jQuery, Bootstrap, and plyr 

File structure:
```
│  
├── html
|   ├── vtt
|   ├── jpg
|   ├── mp4
│   └── html
└── media
    ├── js
    |   ├── bootrap.js
    |   ├── jquery.js
    |   ├── font-awesome,js
    |   └── data.js (here is script intilalizing plyr)
    ├── css
    |   ├── bootrap.css 
    |   ├── my css
    |   ├── font-awesome,js
    |   └── data.js (here is script intilalizing plyr)
    ├── img
    |   └── jpg's
    ├── blank.mp4
    ├── plyr.min.js
    ├── plyr.css
    ├── plyr.css.map
    └── plyr.svg
```

```html
<video controls crossorigin playsinline id=player poster="local path to poster">
    <source src="local path to file" type="video/mp4" />
    <track kind="captions" label="English" srclang="en" src="local path to vtt file" default="" \>
</video>

<script src="../media/plyr.min.js"></script>
```

```js
document.addEventListener('DOMContentLoaded', () => { 
  const player = new Plyr('#player', {
    iconUrl: '../media/plyr.svg'
  });
});

**Comment by sampotts** [comment] 2018-04-28 22:33
Any errors in the console? What’s the HTML for a button look like?

**Comment by sampotts** [comment] 2018-04-28 22:35
Are you seeing this on https://plyr.io? It was a checkbox in the template you removed :)

**Comment by buszmen201** [comment] 2018-04-29 10:31
In console is no errors.
After schich on `debug: true`
```js
{
  "enabled": true,
  "title": "",
  "debug": true,
  "autoplay": false,
  "autopause": true,
  "seekTime": 10,
  "volume": 1,
  "muted": false,
  "duration": null,
  "displayDuration": true,
  "invertTime": true,
  "toggleInvert": true,
  "ratio": "16:9",
  "clickToPlay": true,
  "hideControls": true,
  "showPosterOnEnd": false,
  "disableContextMenu": true,
  "loadSprite": false,
  "iconPrefix": "plyr",
  "iconUrl": "../media/plyr.svg",
  "blankVideo": "https://cdn.plyr.io/static/blank.mp4",
  "quality": {
    "default": 576,
    "options": [
      4320,
      2880,
      2160,
      1440,
      1080,
      720,
      576,
      480,
      360,
      240,
      "default"
    ]
  },
  "loop": {
    "active": false
  },
  "speed": {
    "selected": 1,
    "options": [
      0.5,
      0.75,
      1,
      1.25,
      1.5,
      1.75,
      2
    ]
  },
  "keyboard": {
    "focused": true,
    "global": false
  },
  "tooltips": {
    "controls": false,
    "seek": true
  },
  "captions": {
    "active": false,
    "language": "pl"
  },
  "fullscreen": {
    "enabled": true,
    "fallback": true,
    "iosNative": false
  },
  "storage": {
    "enabled": true,
    "key": "plyr"
  },
  "controls": [
    "play-large",
    "play",
    "progress",
    "current-time",
    "mute",
    "volume",
    "captions",
    "settings",
    "pip",
    "airplay",
    "fullscreen"
  ],
  "settings": [
    "captions",
    "quality",
    "speed"
  ],
  "i18n": {
    "restart": "Restart",
    "rewind": "Rewind {seektime} secs",
    "play": "Play",
    "pause": "Pause",
    "fastForward": "Forward {seektime} secs",
    "seek": "Seek",
    "played": "Played",
    "buffered": "Buffered",
    "currentTime": "Current time",
    "duration": "Duration",
    "volume": "Volume",
    "mute": "Mute",
    "unmute": "Unmute",
    "enableCaptions": "Enable captions",
    "disableCaptions": "Disable captions",
    "enterFullscreen": "Enter fullscreen",
    "exitFullscreen": "Exit fullscreen",
    "frameTitle": "Player for {title}",
    "captions": "Captions",
    "settings": "Settings",
    "speed": "Speed",
    "normal": "Normal",
    "quality": "Quality",
    "loop": "Loop",
    "start": "Start",
    "end": "End",
    "all": "All",
    "reset": "Reset",
    "disabled": "Disabled",
    "enabled": "Enabled",
    "advertisement": "Ad"
  },
  "urls": {
    "vimeo": {
      "api": "https://player.vimeo.com/api/player.js"
    },
    "youtube": {
      "api": "https://www.youtube.com/iframe_api"
    },
    "googleIMA": {
      "api": "https://imasdk.googleapis.com/js/sdkloader/ima3.js"
    }
  },
  "listeners": {
    "seek": null,
    "play": null,
    "pause": null,
    "restart": null,
    "rewind": null,
    "fastForward": null,
    "mute": null,
    "volume": null,
    "captions": null,
    "fullscreen": null,
    "pip": null,
    "airplay": null,
    "speed": null,
    "quality": null,
    "loop": null,
    "language": null
  },
  "events": [
    "ended",
    "progress",
    "stalled",
    "playing",
    "waiting",
    "canplay",
    "canplaythrough",
    "loadstart",
    "loadeddata",
    "loadedmetadata",
    "timeupdate",
    "volumechange",
    "play",
    "pause",
    "error",
    "seeking",
    "seeked",
    "emptied",
    "ratechange",
    "cuechange",
    "enterfullscreen",
    "exitfullscreen",
    "captionsenabled",
    "captionsdisabled",
    "languagechange",
    "controlshidden",
    "controlsshown",
    "ready",
    "statechange",
    "qualitychange",
    "qualityrequested",
    "adsloaded",
    "adscontentpause",
    "adscontentresume",
    "adstarted",
    "adsmidpoint",
    "adscomplete",
    "adsallcomplete",
    "adsimpression",
    "adsclick"
  ],
  "selectors": {
    "editable": "input, textarea, select, [contenteditable]",
    "container": ".plyr",
    "controls": {
      "container": null,
      "wrapper": ".plyr__controls"
    },
    "labels": "[data-plyr]",
    "buttons": {
      "play": "[data-plyr=\"play\"]",
      "pause": "[data-plyr=\"pause\"]",
      "restart": "[data-plyr=\"restart\"]",
      "rewind": "[data-plyr=\"rewind\"]",
      "fastForward": "[data-plyr=\"fast-forward\"]",
      "mute": "[data-plyr=\"mute\"]",
      "captions": "[data-plyr=\"captions\"]",
      "fullscreen": "[data-plyr=\"fullscreen\"]",
      "pip": "[data-plyr=\"pip\"]",
      "airplay": "[data-plyr=\"airplay\"]",
      "settings": "[data-plyr=\"settings\"]",
      "loop": "[data-plyr=\"loop\"]"
    },
    "inputs": {
      "seek": "[data-plyr=\"seek\"]",
      "volume": "[data-plyr=\"volume\"]",
      "speed": "[data-plyr=\"speed\"]",
      "language": "[data-plyr=\"language\"]",
      "quality": "[data-plyr=\"quality\"]"
    },
    "display": {
      "currentTime": ".plyr__time--current",
      "duration": ".plyr__time--duration",
      "buffer": ".plyr__progress--buffer",
      "played": ".plyr__progress--played",
      "loop": ".plyr__progress--loop",
      "volume": ".plyr__volume--display"
    },
    "progress": ".plyr__progress",
    "captions": ".plyr__captions",
    "menu": {
      "quality": ".js-plyr__menu__list--quality"
    }
  },
  "classNames": {
    "video": "plyr__video-wrapper",
    "embed": "plyr__video-embed",
    "ads": "plyr__ads",
    "control": "plyr__control",
    "type": "plyr--{0}",
    "provider": "plyr--{0}",
    "stopped": "plyr--stopped",
    "playing": "plyr--playing",
    "loading": "plyr--loading",
    "error": "plyr--has-error",
    "hover": "plyr--hover",
    "tooltip": "plyr__tooltip",
    "cues": "plyr__cues",
    "hidden": "plyr__sr-only",
    "hideControls": "plyr--hide-controls",
    "isIos": "plyr--is-ios",
    "isTouch": "plyr--is-touch",
    "uiSupported": "plyr--full-ui",
    "noTransition": "plyr--no-transition",
    "menu": {
      "value": "plyr__menu__value",
      "badge": "plyr__badge",
      "open": "plyr--menu-open"
    },
    "captions": {
      "enabled": "plyr--captions-enabled",
      "active": "plyr--captions-active"
    },
    "fullscreen": {
      "enabled": "plyr--fullscreen-enabled",
      "fallback": "plyr--fullscreen-fallback"
    },
    "pip": {
      "supported": "plyr--pip-supported",
      "active": "plyr--pip-active"
    },
    "airplay": {
      "supported": "plyr--airplay-supported",
      "active": "plyr--airplay-active"
    },
    "tabFocus": "plyr__tab-focus"
  },
  "attributes": {
    "embed": {
      "provider": "data-plyr-provider",
      "id": "data-plyr-embed-id"
    }
  },
  "keys": {
    "google": null
  },
  "ads": {
    "enabled": false,
    "publisherId": ""
  },
  "crossorigin": true,
  "playsinline": true
}
```
And here is whole rendered player:

```html
<div tabindex="0" class="plyr plyr--full-ui plyr--video plyr--html5 plyr--is-touch plyr--captions-enabled plyr--captions-active plyr--stopped plyr--fullscreen-enabled">
    <div class="plyr__video-wrapper">
        <video crossorigin="" playsinline="" id="player" poster="LHsN-In_VCk.jpg">
            <source src="2018-04-25T151851.000Z -- Noisia Radio S04E17.mp4" type="video/mp4" width="720">
            <track kind="captions" label="English" srclang="en" src="2018-04-25T151851.000Z -- Noisia Radio S04E17.vtt" default="">
        </video>
    </div>
    <div class="plyr__captions"></div>
    <button type="button" class="plyr__control plyr__control--overlaid" data-plyr="play" aria-pressed="false">
        <svg role="presentation">
            <use xlink:href="../media/plyr.svg#plyr-play"></use>
        </svg>
        <span class="plyr__sr-only">Play</span>
    </button>
    <div class="plyr__controls">
        <button type="button" class="plyr__control" aria-pressed="false" aria-label="Play" data-plyr="play">
            <svg class="icon--pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-pause"></use>
            </svg>
            <svg class="icon--not-pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-play"></use>
            </svg>
            <span class="label--pressed plyr__sr-only">Pause</span>
            <span class="label--not-pressed plyr__sr-only">Play</span>
        </button>
        <div class="plyr__progress">
            <label for="plyr-seek-1008" class="plyr__sr-only">Seek</label>
            <input data-plyr="seek" min="0" max="100" step="0.01" value="0" autocomplete="off" id="plyr-seek-1008"
                type="range">
            <progress class="plyr__progress--buffer" min="0" max="100" value="0">% buffered</progress>
            <span role="tooltip" class="plyr__tooltip">00:00</span>
        </div>
        <div class="plyr__time">1:00:17</div>
        <button type="button" class="plyr__control" aria-pressed="false" aria-label="Mute" data-plyr="mute">
            <svg class="icon--pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-muted"></use>
            </svg>
            <svg class="icon--not-pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-volume"></use>
            </svg>
            <span class="label--pressed plyr__sr-only">Unmute</span>
            <span class="label--not-pressed plyr__sr-only">Mute</span>
        </button>
        <div class="plyr__volume">
            <label for="plyr-volume-1008" class="plyr__sr-only">Volume</label>
            <input data-plyr="volume" min="0" max="1" step="0.05" value="1" autocomplete="off" id="plyr-volume-1008"
                type="range">
        </div>
        <button type="button" class="plyr__control" aria-pressed="true" aria-label="Enable captions" data-plyr="captions">
            <svg class="icon--pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-captions-on"></use>
            </svg>
            <svg class="icon--not-pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-captions-off"></use>
            </svg>
            <span class="label--pressed plyr__sr-only">Disable captions</span>
            <span class="label--not-pressed plyr__sr-only">Enable captions</span>
        </button>
        <div class="plyr__menu">
            <button id="plyr-settings-toggle-1008" aria-haspopup="true" aria-controls="plyr-settings-1008" aria-expanded="false"
                type="button" class="plyr__control" data-plyr="settings">
                <svg role="presentation">
                    <use xlink:href="../media/plyr.svg#plyr-settings"></use>
                </svg>
                <span class="plyr__sr-only">Settings</span>
            </button>
            <form class="plyr__menu__container" id="plyr-settings-1008" aria-hidden="true" aria-labelled-by="plyr-settings-toggle-1008"
                role="tablist" tabindex="-1">
                <div>
                    <div id="plyr-settings-1008-home" aria-hidden="false" aria-labelled-by="plyr-settings-toggle-1008" role="tabpanel">
                        <ul role="tablist">
                            <li role="tab">
                                <button data-plyr="settings" type="button" class="plyr__control plyr__control--forward" id="plyr-settings-1008-captions-tab"
                                    aria-haspopup="true" aria-controls="plyr-settings-1008-captions" aria-expanded="false">Captions
                                    <span class="plyr__menu__value">English</span>
                                </button>
                            </li>
                            <li role="tab" hidden="">
                                <button data-plyr="settings" type="button" class="plyr__control plyr__control--forward" id="plyr-settings-1008-quality-tab"
                                    aria-haspopup="true" aria-controls="plyr-settings-1008-quality" aria-expanded="false">Quality
                                    <span class="plyr__menu__value"></span>
                                </button>
                            </li>
                            <li role="tab">
                                <button data-plyr="settings" type="button" class="plyr__control plyr__control--forward" id="plyr-settings-1008-speed-tab"
                                    aria-haspopup="true" aria-controls="plyr-settings-1008-speed" aria-expanded="false">Speed
                                    <span class="plyr__menu__value">Normal</span>
                                </button>
                            </li>
                        </ul>
                    </div>
                    <div id="plyr-settings-1008-captions" aria-hidden="true" aria-labelled-by="plyr-settings-1008-captions-tab"
                        role="tabpanel" tabindex="-1">
                        <button type="button" class="plyr__control plyr__control--back" aria-haspopup="true" aria-controls="plyr-settings-1008-home"
                            aria-expanded="false">Captions</button>
                        <ul>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="language" name="plyr-language" value="" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>Disabled</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="language" name="plyr-language" value="en" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>English
                                    <span class="plyr__menu__value">
                                        <span class="plyr__badge">EN</span>
                                    </span>
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div id="plyr-settings-1008-quality" aria-hidden="true" aria-labelled-by="plyr-settings-1008-quality-tab"
                        role="tabpanel" tabindex="-1" hidden="">
                        <button type="button" class="plyr__control plyr__control--back" aria-haspopup="true" aria-controls="plyr-settings-1008-home"
                            aria-expanded="false">Quality</button>
                        <ul></ul>
                    </div>
                    <div id="plyr-settings-1008-speed" aria-hidden="true" aria-labelled-by="plyr-settings-1008-speed-tab"
                        role="tabpanel" tabindex="-1">
                        <button type="button" class="plyr__control plyr__control--back" aria-haspopup="true" aria-controls="plyr-settings-1008-home"
                            aria-expanded="false">Speed</button>
                        <ul>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="0.5" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>0.5×</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="0.75" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>0.75×</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="1" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>Normal</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="1.25" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>1.25×</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="1.5" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>1.5×</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="1.75" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>1.75×</label>
                            </li>
                            <li>
                                <label class="plyr__control">
                                    <input data-plyr="speed" name="plyr-speed" value="2" checked="false" class="plyr__sr-only"
                                        type="radio">
                                    <span aria-hidden="true"></span>2×</label>
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        </div>
        <button type="button" class="plyr__control" aria-pressed="false" aria-label="Enter fullscreen" data-plyr="fullscreen">
            <svg class="icon--pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-exit-fullscreen"></use>
            </svg>
            <svg class="icon--not-pressed" role="presentation">
                <use xlink:href="../media/plyr.svg#plyr-enter-fullscreen"></use>
            </svg>
            <span class="label--pressed plyr__sr-only">Exit fullscreen</span>
            <span class="label--not-pressed plyr__sr-only">Enter fullscreen</span>
        </button>
    </div>
</div>
````

**Comment by buszmen201** [comment] 2018-04-29 10:58
Anyway, when I don't provide iconUrl (and it's is downloaded from CDN) it's working.

**Comment by friday** [comment] 2018-05-05 15:52
Have you checked that the response mimetype is the same with your local server as the cdn?

**Comment by friday** [comment] 2018-06-01 00:41
I had a related (perhaps a variant of the same) issue just now in Firefox, missing some of the SVG icons on one specific domain.

I had 11/14 icons. One of the missing ones was the settings icon. Not sure about the other 2.

Tested with:
```js
document.querySelectorAll('#sprite-plyr svg symbol').length
```

It turned out to be because I had an outdated svg cache in localStorage. Clearing localStorage fixed it, so it wasn't really a Firefox issue. I just got it in Firefox since I hadn't been using Firefox with that server for a while I guess.

Personally I'd rather avoid using localStorage like this since it never expires. The regular browser cache should handle xhr requests as well, unless I'm missing something? Alternatively we could also store the Plyr version and invalidate the cache when the version doesn't match. Otherwise this would happen every time we add or rename an icon (which isn't very often though).

I used Plyr v3 pre-beta though, so this might be an issue more patient user wouldn't have gotten.

**Comment by sampotts** [comment] 2018-06-01 01:57
Using localstorage is so we don't get a flash of no icons. Localstorage is faster than relying on browser cache. The way it works though, the localstorage is updated every load anyway.

**Comment by friday** [comment] 2018-06-01 02:04
I see. That makes a lot more sense than just using it for caching. But in that case the invalidator must not work in Firefox, as reloading the page should have solved it?

**Comment by sampotts** [comment] 2018-06-01 02:17
Yep should have. I’ll double check the logic later.

**Comment by friday** [comment] 2018-06-08 20:55
I'll try to fix the localStorage issue soon, if no one beats me to it. Will then consider this issue fixed, unless someone shows the opposite.

**Comment by sampotts** [comment] 2018-06-09 01:41
I think I've found the issue. It's meant to work like this:

- Check local storage has a sprite and it if does load from there
- Make the XHR request 
- Update local storage for next page view as well as update sprite in DOM

The problem is if the sprite already exists, it doesn't inject again. I'll get this one done today.

**Comment by friday** [comment] 2018-06-19 16:27
This should be fixed by now. If not, let us know.

**Closed by friday** 2018-06-19 16:27 UTC
Labels: Bug
