### ISSUE TITLE
iosNative: true breaks fullscreen for embeds

### ISSUE THREAD

**Issue by verde-io** [sampotts/plyr#900] opened 2018-04-16 15:55 UTC
Not sure how this is supposed to work, but at the moment setting iosNative to true breaks the fullscreen functionality for Youtube/Vimeo embeds, with the following error being logged when clicking on the fullscreen button:

`TypeError: this.target.webkitEnterFullscreen is not a function. (In 'this.target.webkitEnterFullscreen()', 'this.target.webkitEnterFullscreen' is undefined)`

on [line 2010](https://github.com/sampotts/plyr/blob/e138e6d51e3cd85d85ccbd32674f75a63a3771ef/dist/plyr.js#L2010).

**Comment by MrShakhov** [comment] 2019-06-21 17:52
Hi, guys! Tell me pleace, what is the situation with the solution of this problem?

**Comment by LavrovE** [comment] 2019-11-22 12:24
up

**Comment by alexander-danilenko** [comment] 2020-01-30 15:04
Any updates on this?

**Comment by tmk1991** [comment] 2020-07-26 02:22
Confirmed

**Comment by torstah** [comment] 2020-09-24 11:54
Any news on this?

**Comment by sampotts** [comment] 2023-06-12 10:09
Yep, should be fixed since 3.7.4 
https://github.com/sampotts/plyr/releases/tag/v3.7.4

**Closed by sampotts** 2023-06-12 10:09 UTC
Labels: Bug, In Development

**Comment by lf-devs** [comment] 2023-06-13 10:58
@sampotts - I'm still facing the same issue with the `Plyr` dependency in Chrome and Safari. I'm using iPhone 11 and I tried again by updating `Plyr` from v3.7.3 to v3.7.8. Please help.
