### ISSUE TITLE
[Feature request] Not load iframe until user clicked play button

### ISSUE THREAD

**Issue by CryptorClub** [sampotts/plyr#1669] opened 2020-02-01 14:22 UTC
Hello. This feature request about Youtube/Vimeo embed player

Would be great, if there be option to not load iframe until user clicked on play button. (But in same case load background with thumbnail)

**Comment by CryptorClub** [comment] 2020-02-01 14:54
Here how it looks, this lazy load https://codepen.io/chriscoyier/pen/GRKZryx

**Comment by sampotts** [comment] 2020-02-09 22:07
Duplicate of https://github.com/sampotts/plyr/issues/1620

**Closed by sampotts** 2020-02-09 22:07 UTC
