### ISSUE TITLE
[V3] [3.0.2] Can't leave fullscreen in Firefox

### ISSUE THREAD

**Issue by MBWebTechMariusz** [sampotts/plyr#821] opened 2018-03-20 14:05 UTC
### Expected behaviour
After entering fullscreen in Firefox it is possible to leave fullscreen again via the button.

### Actual behaviour
After entering fullscreen in Firefox you can only leave the fullscreen via ESC, not via the button.

### Environment

- On live: https://plyr.io/
- Browser: Firefox
- Version: 59.0.1
- Operating System: Windows
- Version: 8.1

### Steps to reproduce
- Go to https://plyr.io/ via Firefox
- Enter Fullscreen

**Comment by MBWebTechMariusz** [comment] 2018-03-20 19:18
Found the issue:
See https://developer.mozilla.org/de/docs/Web/API/Vollbild_API, under "Vendor Präfixe".
In Firefox, the fullscreenelement needs a capital S: mozFullScreenElement

So the code around line 7312:
`var element = !this.prefix ? document.fullscreenElement : document[this.prefix + 'FullscreenElement'];
`
Needs to be changed like so:
`var element = !this.prefix ? document.fullscreenElement : this.prefix === 'moz' ? document[this.prefix + 'FullScreenElement'] : document[this.prefix + 'FullscreenElement'];`

**Comment by sampotts** [comment] 2018-03-21 13:26
Found a fix for this. The differences in prefixes and method names is a right PITA with fullscreen but I think I have it nailed now 👍

**Closed** 2018-03-21 13:26 UTC

**Comment by thetre97** [comment] 2018-04-05 17:14
Having the same issue in Chrome now - 

```plyr.min.js?e0c5:1 Uncaught TypeError: document.cancelFullScreen is not a function
    at e.value (plyr.min.js?e0c5:1)
    at e.value (plyr.min.js?e0c5:1)
    at n.eval (plyr.min.js?e0c5:1)
    at i (plyr.min.js?e0c5:1)
    at HTMLButtonElement.eval (plyr.min.js?e0c5:1)
```

**Comment by friday** [comment] 2018-04-05 17:51
@thetre97 Make sure you are using the latest Plyr version. If it still happens, please create a new issue with a code example how to reproduce it (since it's not been known to happen to anyone else).
