### ISSUE TITLE
how to add quality selector in plyr with hls?

### ISSUE THREAD

**Issue by meghaarora099** [sampotts/plyr#1307] opened 2019-01-09 10:10 UTC
i am looking for quality selector feature in plyr with hls . But, i was not able to kindly guide me through this, any kind of suggestion would be appreciated.

TIA

**Comment by sampotts** [comment] 2019-02-18 14:32
Duplicate of https://github.com/sampotts/plyr/issues/1118 - Please search next time 👍

**Closed by sampotts** 2019-02-18 14:32 UTC
