### ISSUE TITLE
Video quality options (HTML5, YouTube, Vimeo)

### ISSUE THREAD

**Issue by donnygunawan93** [sampotts/plyr#218] opened 2016-05-16 18:11 UTC
please add video quality option for youtube

**Comment by SamPotts** [comment] 2016-05-18 08:37
Will do. good idea 👍

**Comment by SamPotts** [comment] 2016-05-25 18:09
From #220 @thelamborghinistory 

> First of all I just want to say I came here from PH and I instantly fell in love with this player (not only I have a crush on it but it also came up at the perfect time on my screen ;)). So big kudos to you guys.

However, I am curious if it's possible to integrate an option to switch quality of a video like YouTube has (I think half of the functionality for such a feature is already done with the plyr.source() method, so there might just remain a nice dropup menu for the resolution options). What do you think?

From #245 @tamanhquyen

> I have created player using your plugins . But i can't change quality on vimeo source . Please help me . Thanks a lot!

**Comment by gino8080** [comment] 2016-06-21 11:06
Definitely need quality option for Vimeo on this great player!

**Comment by Parasoul** [comment] 2016-09-20 09:16
Need the video quality option for Youtube !! ^^

**Comment by masinerija12** [comment] 2016-10-16 19:17
Please add a quality change option for html5.
Would use this on all my sites.
Best looking and fastest html5 player ever!
10/10

**Comment by shutterarmy** [comment] 2016-11-18 04:24
Eagerly waiting for the Quality change Option for YouTube  like all the others. Amazing player BTW!!

**Comment by SamPotts** [comment] 2016-11-18 05:02
It's coming along... 

![image](https://cloud.githubusercontent.com/assets/719092/20419157/68ad4f84-ada8-11e6-8122-e1f4ec5b545c.png)

**Comment by shutterarmy** [comment] 2016-11-23 03:43
Yes!!

**Comment by masinerija12** [comment] 2016-11-24 08:44
Looks awesome man. Can't wait.

**Comment by MelchnerRoman** [comment] 2016-11-25 09:23
+1 need this

**Comment by cwbmuller** [comment] 2016-11-30 07:32
@SamPotts looking great!

**Comment by hutanatu** [comment] 2016-11-30 10:52
Looks awesome man. Can't wait.

**Comment by hitnology** [comment] 2016-12-07 02:47
@SamPotts Can't wait this feature.
I want to change my website and waiting for you since may=.=

**Comment by Abdalrhmam** [comment] 2017-01-01 17:04
Great work

**Comment by DiasFelipe** [comment] 2017-01-31 20:09
Looks awesome, can't wait.

**Comment by singleseeker** [comment] 2017-02-05 06:04
How`s it going?

**Comment by aolko** [comment] 2017-03-06 06:41
Is it done and can be pushed to the master branch?

**Comment by SamPotts** [comment] 2017-03-06 09:24
No, but my baby son is and is growing well. Sorry, he takes priority right now.

**Comment by tonmoy-ajize** [comment] 2017-03-27 14:31
Waiting for this badly.

**Comment by SamPotts** [comment] 2017-03-27 22:53
I've been managing to squeeze in some more time here and there in between changing nappies and getting the little fella to sleep. Sorry it's just been a bit more complicated than previous changes given all the new UI components and having a kid in the middle of it wasn't well planned. 

This is going to be launched along with:

- Multiple caption support
- More advanced loop support
- Speed controls 

I'm getting there just hang in there 👍 

![image](https://cloud.githubusercontent.com/assets/719092/24381493/4697dab8-139c-11e7-951c-373d6c4983bc.png)

**Comment by POPSuL** [comment] 2017-03-27 22:59
Great! :+1:

**Comment by tonmoy-ajize** [comment] 2017-03-27 23:02
It looks great ... Not it became more teasing than before 👍

**Comment by CalebKester** [comment] 2017-03-31 20:35
@SamPotts let's us know if you need help testing this. I'd be happy to help out in what ways I can. I've been using your library in a vuejs project and really enjoying it.

**Comment by SamPotts** [comment] 2017-03-31 21:16
Cool - I'm hoping to get a working version up and running in develop soon. Just trying to find more time.

**Comment by mkdub** [comment] 2017-04-17 21:26
Hey Sam,

How's life juggling the baby and code, I can't even imagine! Hope alls been well.

I am looking forward to your new release of features that's coming our way soon, I had a quick question for you. Will we be able to set the default for the vimeo links to load in HD? I am currently building a website that the user is not able to change controls to the player but I'd still like to load the videos in HD. 

Take care!

**Comment by SamPotts** [comment] 2017-04-17 22:35
Hey,

I'm getting there slowly. I keep chipping away at it when I get a few minutes. 

Vimeo's API is fairly limited and doesn't allow control over the quality like YouTube does unfortunately. It seems to be "auto" the majority of the time for me - mostly loading in HD. 

Nice VWs! I have an R36 wagon and Audi S3 8L myself 👍

**Comment by xdajay** [comment] 2017-05-01 19:35
Hey @SamPotts .

First of all, Thank you for making such a great HTML5 player 👍  
Video Quality option for Direct MP4 Video will be there? 
If yes, Please let me know, Will integrate  on https://burffee.com

**Comment by ewwink** [comment] 2017-05-10 03:43
any update?

**Comment by SamPotts** [comment] 2017-05-10 03:46
Nope, still working on it. You'll see here when there's updates. Sounds like we'll have a load of testers 👍 I'm trying to find time where I can to get it done but as I'm sure you're aware (judging by your avatar) - there's a shortage of time when you have a kid.

**Comment by ewwink** [comment] 2017-05-10 03:51
I understand, OK we will wait and thanks for your work and time.

**Comment by An0nymous0** [comment] 2017-07-21 02:23
Quality selection function What time to launch？

**Comment by sampotts** [comment] 2017-07-21 02:25
See above. Plyr isn't a commercial, paid product. I do it in my *spare time* for *free*.

**Comment by mkdub** [comment] 2017-07-21 02:46
I think if there's enough people here that are requesting certain updates, we should all come together and donate to help Sam. We should make sure it's worth his time to put the effort to make something we all use even greater.

**Comment by tonmoy-ajize** [comment] 2017-07-21 02:50
Totaly agreed to @mkdub .. I am ready to send some help to Sam.

Looking forward to Sam if he can really give us some time ...

**Comment by jwjcmw** [comment] 2017-07-21 03:20
Just a reminder that there is a donate link in the readme...use it (I'm about to).

**Comment by sampotts** [comment] 2017-07-21 04:13
Thanks for the donations guys. Really nice of you. I'll set aside as much time I can this weekend to make progress on the remaining items on my list. 👍

**Comment by mkdub** [comment] 2017-07-21 04:14
To save people time, as we all now understand time=money. 

Here is the direct link to [donate](https://www.paypal.me/pottsy/20usd). Anything you can put in will go a long way, it's not just for this feature but everything else that will keep this great plugin at the top.

**Comment by fiveDust** [comment] 2017-07-24 17:59
@mkdub Awesome, just sent some support Sam's way. Very much looking forward to seeing the HTML5 HD switch come to live. I can already see it in the dev branch for Youtube. Awesome.

**Comment by aolko** [comment] 2017-09-05 09:18
_...and then most people forgot about this_

**Comment by sampotts** [comment] 2017-09-05 10:05
> _...and then most people forgot about this_

I'm not sure what you mean? No one's forgotten and I've been putting in as much time on it as I can. So far it only works for YouTube and their API is pretty flaky in this area. The video will play back with "auto" as the default (they determine it based on connection) and from there you can only increase quality it seems. i.e. attempting to go from 720P to 1080P is fine but downgrading doesn't seem to work. The way the API works is you "suggest" a quality and it may or may not change the actual quality - you listen for an event to indicate the quality has changed. 

Vimeo does not expose the ability to toggle from SD to HD and vice versa. They don't allow a lot in their API but what they do allow works well. 

HTML5 quality control will have to come later, I'm not sure how to tackle that one quite yet. 

The main delay is that I'm trying to do too much at once really, the main features in v3 include:

- AirPlay support
- PiP support
- iOS inline playback support
- Improvements to the setup (a proper constructor) 
- Multi language captions support 
- Improvements to looping options

...accompanied with a fairly hefty re-write in preparation for ES6 and making the lib more modular.

**Comment by fiveDust** [comment] 2017-09-05 10:13
@sampotts awesome Sam. Thanks for the feedback and thanks for putting the effort in besides busy family life! In terms of the HD toggle for HTML5, would it be possible to have a way to extend the controls with a view / icon and registering a custom callback so those who need it might be able to implement it themselves? Same for a HTML5 download button.

**Comment by EnziinSystem** [comment] 2017-10-05 04:26
@sampotts , thanks so much.

**Comment by POPSuL** [comment] 2017-10-11 05:32
@sampotts, the quality selector will be implemented only for YouTube/Vimeo, or for `type: 'video'` will also be implemented?

**Comment by ajoykarmakar459** [comment] 2017-10-14 07:24
When the quality features add in your product?

**Comment by SadeqRasheed** [comment] 2017-10-23 19:52
Thank you for this amazing player, can i get an early access somehow ? i really need the quality options even if they are not stable 💃

**Comment by friday** [comment] 2017-10-23 20:06
@SadeqRasheed: You can access v3 in the develop-branch. I'm already doing that (only for subtitles), but it's not recommended. Some features are partially implemented and will break unless you disable them.

**Comment by sampotts** [comment] 2017-10-24 00:00
Yeah as @friday said really. It's still buggy at the moment. I am chipping away at it as much as I can and am close but still doing a lot of testing and fixing bugs. This version should be a lot more stable as a result but again, I can't guarantee when it will be done other than as soon as I can get it out the door. 

As for @POPSuL for now it'll be YouTube only. Vimeo doesn't expose their HD toggle. HTML5 will follow soon after (and should be relatively straight forward) but I want to get it out rather than keep delaying.

**Comment by jeffreymeng** [comment] 2017-12-02 07:56
I've just found your library. It's Awesome!

Just one question.

Is there going to be some sort of an api to add your own options to the popup?
Like a function to add a component, and links within that component, and each link runs a callback function(or something like that)?

**Comment by mayeaux** [comment] 2017-12-09 05:26
Could really use this 🙃 +1

**Comment by marceloavf** [comment] 2017-12-09 13:59
Any update about YouTube option @sampotts ?
Thanks!

**Comment by aolko** [comment] 2017-12-13 14:02
any update on html5 ones?

**Comment by StefansArya** [comment] 2018-01-09 05:13
switch to the development branch to see the current progress

**Comment by LukasMarques** [comment] 2018-01-31 13:49
Is it possible to implement a quality selector for video element? I think this is much more easier and in my case, for example could be used with AWS S3.
I was thinkin in something like this:
`  <video poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg" controls crossorigin>
    
    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4" type="video/mp4" quality="720p">
    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-FullHD.mp4" type="video/mp4" quality="1080p">
  </video>`

**Comment by sampotts** [comment] 2018-01-31 22:25
The theory part is easy. Yes, it's easy in _theory_. Depends if we want to support multiple source formats etc - e.g. webm with fallback to mp4, etc

**Comment by ewwink** [comment] 2018-02-01 07:13
wow.... after 2 year still not released, it should be not very hard. After my comment above few days later I created plugin for Clappr for this functionality. just for idea https://github.com/ewwink/clappr-youtube-plugin

**Comment by aolko** [comment] 2018-02-01 08:51
@ewwink as you can read above:

> I've been putting in as much time on it as I can

**Comment by sampotts** [comment] 2018-02-01 10:23
He struggles with reading I think. 

@ewwink Going by your avatar, you either have a child or are a child yourself so you know how much time they take up. I must have missed your pull request to actually help? Did I miss a donation from yourself? If so I'm sorry!!

I have to repeat myself over and over seemingly; open source is quite often written by people **for free** in their **spare time**. Be thankful, contribute, assist. Anything but sit back and moan like a child. 

v3 is in beta. Check it out. It doesn't have HTML5 quality options yet but I will work on that next. It was a major rewrite so it took some time. I hope that's ok with you. I'm sorry I let you down!!

**Comment by LukasMarques** [comment] 2018-02-01 10:35
Ok, thanks for your time!

**Comment by fiveDust** [comment] 2018-02-01 10:42
No need to justify, @sampotts. I think I can speak for the majority here when I say that we're grateful for all your effort you put in, in the time you have.

**Comment by friday** [comment] 2018-02-01 10:55
Exactly. I don't have a family/child but I haven't been able to use my spare time to develop and maintain something as popular as plyr. So instead I'm very grateful Sam has pulled it off.

**Comment by sampotts** [comment] 2018-02-01 22:38
Thanks fellas 👍

**Comment by mkdub** [comment] 2018-02-02 00:10
Let us know if there's anything we can do to help, test, write, whatever you need.

**Comment by Droppers** [comment] 2018-03-11 21:42
My compliments for this player, so far it works really smooth!

I don't want to be rude, but is there an ETA for the HTML5 quality options? A few months, half year?

**Comment by friday** [comment] 2018-03-11 22:43
@Droppers This is part of https://github.com/sampotts/plyr/issues/766 due to release very soon. It is implemented, but not for HTML5 yet, and the youtube api seems to ignore quality change requests (https://github.com/sampotts/plyr/issues/793#issuecomment-371278521).

It's hard to do this smoothly with HTML5 video unless it's a stream btw. I'm not sure but I imagine this is why html5 video hasn't been implemented yet.

**Comment by Droppers** [comment] 2018-03-12 09:58
@friday I am probably missing something, but I don't get why HTML5 video would be difficult.

I will try to implement it myself and I will experience it.

**Comment by sampotts** [comment] 2018-03-12 09:59
Go for it. Just make sure you remember how the cascading sources work, i.e. if webm is supported, that's used, if not mp4, etc

**Comment by friday** [comment] 2018-03-12 11:07
I think it's easy to implement, but hard to implement *smoothly*, without pausing or getting jumps. HTML5 Media Fragments for example aren't that precise/granular and neither is the html5 `timeupdate` event. For a smooth effect you may have to preload another html5 video and swap.

Good luck!

**Comment by fiveDust** [comment] 2018-03-12 12:01
@Droppers , cool. Please leave a note here how you're getting on with that.

**Comment by samanmohamadi** [comment] 2018-03-30 19:14
Is there any future plan to support changing video quality using shaka player?

**Comment by sampotts** [comment] 2018-04-01 12:53
I'm working on the HTML5 quality selection at the moment. Will look at Shaka after...

**Comment by friday** [comment] 2018-04-01 13:56
Perhaps you could implement the vanilla HTML5 video first, but allow overriding the actual switching with an event listener? That way you wouldn't have to detect, implement and support individual APIs like shaka, hls.js and dash.js but still work with them. Getting the sources list should be the same for all of them right?

**Comment by sampotts** [comment] 2018-04-01 14:00
I think they'd be similar but I'm really not too familiar with Shaka, HLS, etc. I really need to brush up in those areas. 

The way I'm doing it currently is by using markup like this:

```html
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.webm?480" type="video/webm" size="480">
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4?480" type="video/mp4" size="480">

<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.webm?720" type="video/webm" size="720">
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4?720" type="video/mp4" size="720">

<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.webm?1080" type="video/webm" size="1080">
<source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4?1080" type="video/mp4" size="1080">
```

The issue I foresee is the compatibility of manual selection vs selection via media queries so I'm going to have to do a bit of testing there...

**Comment by friday** [comment] 2018-04-01 14:18
With hls you can also add sources via script. But I don't think it matters. They should end up as iterable child nodes of the video element in the end.

Manual vs automatic switching could be a problem. I don't know much about it, but Imagine it could be handled in an event listener-implementation as well in that case.

**Comment by sampotts** [comment] 2018-04-01 14:19
I'm not sure the native element fires an event when it switches via media query. Perhaps `loadstart` but I'd have to do more testing.

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by sampotts** [comment] 2018-04-01 14:46
The good news is I have the basic functionality working. There is a flash while the new source loads and the poster image is shown. I'm not really sure how that can be avoided other than somehow preloading the other video which would get really complex I'd imagine. Currently it's just swapping out the source.

**Comment by sampotts** [comment] 2018-04-02 12:51
So it looks like my solution with the HTML5 quality selection breaks the media query functionality anyway so I think they'd be mutually exclusive. It's a shame there's no way to set an `active` attribute on the `<source>` element to force it to be active. Also `disabled` while we're at it. 

Anyhow, I've pushed `v3.1.0-beta.1` which includes HTML5 quality selection. I still need to document it properly but effectively you specify a `size` attribute on the `<source>` elements and then a menu is created based on that. You can have multiple `<source>` for the same size with different mime types so the cascading `<source>` mechanism works as before. 

Check it out here:
https://plyr.io/beta

**Comment by aolko** [comment] 2018-04-03 05:55
btw, also peek at this implementation (for a different player) https://github.com/clappr/clappr-level-selector-plugin

**Comment by sampotts** [comment] 2018-04-03 14:26
@aolko Not sure what's going on in that plugin. Pretty bad code: inconsistent formatting, strange variable names, and no comments. 

So, I pushed this to master and it's now up at https://plyr.io

**Comment by zacksiri** [comment] 2018-04-25 05:32
@sampotts will this work for HLS as well?

**Comment by friday** [comment] 2018-08-08 02:30
Closing since it's implemented now for HTML5. For Vimeo it's not possible. For YouTube it was supported. Sam implemented it, but YouTube remove the support on their end shortly after :( hls.js, dash.js and Shaka player is still not supported. There are a few assumptions in the architecture that makes this a little hard to implement.

**Closed by friday** 2018-08-08 02:30 UTC
Labels: Feature, In Development

**Comment by mu7mdmagdy** [comment] 2020-10-16 23:36
there is not way to add quality list for vimeo ?? after api V.3 i think it become easier !

**Comment by AliHaiider** [comment] 2020-11-13 04:35
@friday @sampotts any update about to add Quality for vimeo video?

**Comment by medzhidov** [comment] 2021-02-06 01:28
I cant believe, that it is still not released 😢

**Comment by medzhidov** [comment] 2021-02-06 01:30
@friday here is official vimeo api to get\change quality:
https://github.com/vimeo/player.js/

**Comment by sampotts** [comment] 2021-02-06 02:24
I'm well aware of the Vimeo JS SDK. Plyr already uses it. However quality selection is reserved for paid accounts. Quality selection is already supported and documented for HTML5. YouTube's API for it is merely allows suggesting a quality level and in reality it's ignored 99.9% of the time. It useless.

**Comment by medzhidov** [comment] 2021-02-07 20:18
@sampotts It is useful, because youtube\vimeo may set 720p for default, bases on internet connection, but users want to see it in 1080p, because their connection support it. And what is problem with paid vimeo accounts? I can give to developers access to my paid vimeo account, it is not problem. We want to use this player in our projects, but quality selection is really important feature.

**Comment by sampotts** [comment] 2021-02-07 20:25
I don't disagree that it's useful. However, as I said, for YouTube their API is useless for it. I opened a bug and they closed it as expected behavior. You could try again. 

As for Vimeo, I'd need access to a paid account or at least a video from a paid account then I could give it a go. I'm surprised no ones given it a go and opened a PR if it's that critical.

**Comment by medzhidov** [comment] 2021-02-07 20:36
@sampotts i can help you with this, can you mail me at ilyamedzhidov@yandex.ru? Or we can connect via telegram @ilyamedzhidov, i will give you access to account or can upload and setup any video for tests.

**Comment by medzhidov** [comment] 2021-02-07 20:41
@sampotts i did it just now, link to video:
https://vimeo.com/509541849

**Comment by sampotts** [comment] 2021-02-07 20:42
Thanks, I'll take a look.

**Comment by Timur0076565** [comment] 2021-05-13 19:25
hi!
Is there currently a video quality option for YouTube?

**Comment by sampotts** [comment] 2021-05-14 07:22
@Timur0076565 See my comment further up https://github.com/sampotts/plyr/issues/218#issuecomment-774754457

**Comment by Timur0076565** [comment] 2021-05-25 11:36
Can I change the default YouTube controls from 0 to 1?
This code doesn't work:
<iframe
  :src="`${data.src}?controls=1`"
  allowfullscreen
  allowtransparency
  allow="autoplay"
></iframe>

**Comment by Timur0076565** [comment] 2021-05-27 19:41
@sampotts 
Can I change the default YouTube controls from 0 to 1?
This code doesn't work:

<iframe :src="`${data.src}?controls=1`" allowfullscreen allowtransparency allow="autoplay" ></iframe>

**Comment by medzhidov** [comment] 2021-05-27 20:47
> @sampotts
> Can I change the default YouTube controls from 0 to 1?
> This code doesn't work:
> 
> <iframe :src="`${data.src}?controls=1`" allowfullscreen allowtransparency allow="autoplay" ></iframe>

Stupid question. If you wanna use default controls - add default youtube embed with no plyr.

**Comment by Timur0076565** [comment] 2021-05-27 21:02
@medzhidov, stupid answer!!!! I wanna use plyr with default youtube controls. This is vary important for my player. If you such a very smart person, tell me how i can do it!

**Comment by medzhidov** [comment] 2021-05-27 21:05
I guess Plyr parse link and take only videoId from url, so any params in your link will ignored

**Comment by medzhidov** [comment] 2021-05-27 21:07
> @medzhidov, stupid answer!!!! I wanna use plyr with default youtube controls. This is vary important for my player. If you such a very smart person, tell me how i can do it!

I guess Plyr parse link and take only videoId from url, so any params in your link will ignored

**Comment by Timur0076565** [comment] 2021-05-27 21:10
@medzhidov, yes, I already understood that !!
I need some kind of solution how to add YouTube controls using plyr.
Do you have an ideas?

**Comment by Timur0076565** [comment] 2021-05-27 21:18
@medzhidov ???

**Comment by medzhidov** [comment] 2021-05-27 21:18
> @medzhidov, yes, I already understood that !!
> I need some kind of solution how to add YouTube controls using plyr.
> Do you have an ideas?

Fork this repo and do what you want)

**Comment by Timur0076565** [comment] 2021-05-27 21:21
@medzhidov, Илья, по-моему я задал вполне адекватный вопрос, как мне включить controls = 1, ты же вместо того чтобы подсказать пишешь мне какую то фигню, я повторюсь, если ты такой умный парень, подскажи решение или не лез со своими "Stupid question"!

**Comment by Timur0076565** [comment] 2021-05-27 21:22
@medzhidov, А для чего мне Ютубовские контроллеры в этом плеере - это мое личное дело)

**Comment by medzhidov** [comment] 2021-05-27 21:25
@Timur0076565 i answered your question - fork this repo and change youtube embedding for you needs. Stop spam here

**Comment by Edu4rdob** [comment] 2021-11-16 11:35
Has anyone been able to validate the option for quality exchange recently?

**Comment by Raprodent** [comment] 2022-01-24 14:18
Has any1 found new tags for the itag format? 4K with audio?

**Comment by jelkomme** [comment] 2023-04-03 04:16
@sampotts Could you provide an update on the status of this feature? Has there been any addition of a quality option for playing YouTube videos? If not, it would be highly beneficial if the player could play videos in HD by default.

**Comment by jelkomme** [comment] 2023-04-03 04:17
maybe you can add a feature to AUTO Play Videos in HD by default!?

**Comment by sampotts** [comment] 2023-04-03 04:25
@jelkomme If you've not gathered already, it's not something Plyr has any control over. 

> The changes explained below have been in effect for more than one year. This update merely aligns the documentation with current functionality:
>
> The getPlaybackQuality, setPlaybackQuality, and getAvailableQualityLevels functions are no longer supported. In particular, calls to setPlaybackQuality will be no-op functions, meaning they will not actually have any impact on the viewer's playback experience.

Source: https://developers.google.com/youtube/iframe_api_reference#october-24,-2019

I found this out before this was updated. If you want it restored, I'd suggest reaching out to YouTube/Google, but I don't fancy your chances. Good luck!

**Comment by jelkomme** [comment] 2023-04-03 04:32
@sampotts Hi, thanks for the quick response. I just need a player for my website, it can even be the standard YouTube player without a Plyr skin, as long as it has copyright protection (i.e. it doesn't allow clicking on the title, sharing, checking the source file code URL of the video, etc.).  like its already beeng integrated withing your player by this WP-plugin: https://wordpress.org/plugins/protected-video/ - so like you see in the plugin its possble to add some sort of "protection".

Would you be able to take on such a custom job because i need that quality check for my videos?
