### ISSUE TITLE
Vimeo Fullscreen ratio problem

### ISSUE THREAD

**Issue by mithri** [sampotts/plyr#885] opened 2018-04-11 11:47 UTC
### Expected behaviour
Fullscreen 1:1 ratio as set in the player options
### Actual behaviour
In fullscreen the vimeo video is cropped.

Demo:
https://app.fitmit5.de/video-test-plyr.html

Thanks for helping!

**Comment by sampotts** [comment] 2018-04-11 11:57
Duplicate of https://github.com/sampotts/plyr/issues/854

**Closed by sampotts** 2018-04-11 11:57 UTC
