### ISSUE TITLE
Vimeo + Android Chrome controls not working

### ISSUE THREAD

**Issue by bogdanfer** [sampotts/plyr#549] opened 2017-03-29 09:04 UTC
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Video enters fullscreen player and user should be able to play/pause, go to time, enable/disable HD or toggle volume.
### Actual behaviour
Video enters fullscreen player but the user is not able to click the controls. 

### Environment

- Browser: Chrome 
- Version:  56.0.2924.87
- Operating System: Android 
- Version: 7.0

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 
- Go to plyr.com on mobile (android, chrome) 
- select vimeo 
- play 
- try to use full screen controls

**Comment by iamrobert** [comment] 2017-04-05 05:07
Also sane issue: https://github.com/Selz/plyr/issues/497

**Comment by friday** [comment] 2018-05-30 01:16
Duplicate of #497

**Closed by friday** 2018-05-30 01:16 UTC
