### ISSUE TITLE
controls.md is outdated. How to set up my custom controls?

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#847] opened 2018-03-29 12:11 UTC
I want to modify (rearrange a bit) controls. How can I do this?

On version v2 I followed `controls.md` manual, but it is not relevant anymore.
I took html template from it and just passed to the constructor (prop `controls`), but it doesn't work. You can see this codepen: 
https://codepen.io/yuriyku/pen/ZxaNPa

How can I do this properly? Can you please provide a working template?

Thanks!

**Comment by sampotts** [comment] 2018-03-29 12:11
This is a duplicate of #812 - please check before raising new issues

**Closed by sampotts** 2018-03-29 12:11 UTC

**Comment by yuriykuzin** [comment] 2018-03-29 12:13
Yep, sorry. Just found that.

**Comment by sampotts** [comment] 2018-03-29 12:42
All good mate 👍
