### ISSUE TITLE
YouTube titlebar showing when user is logged in

### ISSUE THREAD

**Issue by mariopacio** [sampotts/plyr#793] opened 2018-02-23 13:41 UTC
Players affected:
- [X] YouTube
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] Vimeo

### Steps to reproduce 
- all youtube players

I'm trying to hide additional information such as related videos, video title and others, but it is not working. Has YouTube changed anything on api?

**Comment by sampotts** [comment] 2018-02-23 13:44
It looks the same to me on here:
https://plyr.io/beta/#youtube

![image](https://user-images.githubusercontent.com/719092/36596975-c167ea34-18fb-11e8-9572-823242137725.png)

And then playing the logo disappears as expected?

**Comment by mariopacio** [comment] 2018-02-23 14:07
https://plyr.io/beta/#youtube

Result:
![image](https://user-images.githubusercontent.com/5333657/36598014-9f930ce4-1889-11e8-9c8f-9685fe33d711.png)

**Comment by sampotts** [comment] 2018-02-23 14:20
Very strange. Must be a language/location thing. Someone else also raised this recently...

**Comment by friday** [comment] 2018-02-23 21:13
I just tried it when logged in to youtube and couldn't reproduce.

Are you behind some kind for proxy/centralized browser cache? They sometimes could mess things up by ignoring query parameters. I thought this was a problem of the past though.

**Comment by mariopacio** [comment] 2018-02-26 14:29
@friday I'm not using any proxy :(

**Comment by malinushj** [comment] 2018-03-07 20:45
@sampotts @friday Hello guys!
I think Youtube might have changed some things again..
The youtube quality switched doesn't work. Neither locally nor on the official example page (https://plyr.io/beta/#youtube).

This could be another issue but the title of this one applies to this problem as well.

![screenshot from 2018-03-07 22-41-45](https://user-images.githubusercontent.com/22645119/37117170-20366c50-2259-11e8-9ab7-f3af7eac7b1a.png)

**Comment by friday** [comment] 2018-03-08 07:27
Yeah, it's a different issue but at least easy to replicate.

**Comment by sampotts** [comment] 2018-03-08 07:30
The problem here is with YouTube you *request* the quality you'd like but you might not necessarily get what you wanted. I make a note of it here:
https://github.com/sampotts/plyr/tree/beta#youtube-only

A bit lame but that's their API :(

**Comment by friday** [comment] 2018-03-08 07:45
I can't find any case when the quality change request is met. Same problem here though: https://developers.google.com/youtube/youtube_player_demo Changing quality with the built in controls work, but using the api controls below doesn't.

**Comment by malinushj** [comment] 2018-03-10 11:01
@friday @sampotts So what I ended up doing... kinda hacky and Youtube still selects what it thinks best but it has a higher success rate at the cost of degraded user experience (more load time and jumpy interruption).
```ts
player.on("qualityrequested", () => {
    if (!player.config.quality || !player.config.quality.selected) return;

    const id = player.embed.getVideoData().video_id;
    const currentTime = player.embed.getCurrentTime();
    player.embed.loadVideoById(id, currentTime, player.config.quality.selected);
    // delete needed to prevent load loop, loadVideoById also fires qualityrequested
    delete player.config.quality.selected;
});
```

**Comment by sampotts** [comment] 2018-03-10 13:03
@malinushj I actually fire that event and handle the requesting so could build that into Plyr itself. It's a shame the YouTube API works that way. I'd raise a bug but every time I've done that they just close issues and say its' meant to be that way (broken!) 😂

**Comment by sampotts** [comment] 2018-03-10 13:12
I've raised a bug but it's pretty pointless I think. They'll just say "that's how it's meant to work" effectively. 
https://issuetracker.google.com/issues/74463069

To me it seems like poor design. Basically they've said "We've created this API method that may or may not work depending on how lucky you are". They should call it `.maybeSetQualityPrettyPlease()`. 

We'll see.

**Comment by friday** [comment] 2018-05-26 18:46
Closing as a duplicate of #976 (this issue is older but has derailed a bit).

**Closed by friday** 2018-05-26 18:46 UTC
