### ISSUE TITLE
audio player connect twice

### ISSUE THREAD

**Issue by rcasunshare** [sampotts/plyr#539] opened 2017-03-17 11:08 UTC
- [x ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

Why does the audio player connect twice when playing live stream icecast?

### Environment

- Browser: all
- Version:  all
- Operating System: all
- Version: all

Players affected:
- [ ] HTML5 Video
- [x ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

**Comment by SamPotts** [comment] 2017-03-17 11:10
No idea - you're on your own with that one. 

Remember that Plyr is just an abstraction for the ***native*** HTML5 players so if 9 times out of 10 issues like this are present in the native players.

**Comment by rcasunshare** [comment] 2017-03-17 11:18
It's weird because with other players I do not only happen with Plyr, when you click play you connect twice but the audio is only one, in the Icecast record it appears as a double client with the same IP.

**Comment by jpmurray** [comment] 2017-06-07 01:07
I noticed this also today, and, to me it seems related to the fact that HTML5 player (at least on chrome) is preloading the file. When adding `preload="none"` to the audio tag, it will only load one stream.

**Comment by raghavendra89** [comment] 2018-01-24 15:50
I had the same issue. From a stackoverflow answer I found that the issue is related to autoplay attribute. You can remove the autoplay and call the play function on video element when the Dom is ready. 

https://stackoverflow.com/questions/5927573/html5-video-playing-twice-audio-doubled-with-jquery-append#answer-12837158

**Comment by sampotts** [comment] 2018-03-22 07:41
I think this is fixed now in v3? Feel free to re-open if that's not the case 👍

**Closed by sampotts** 2018-03-22 07:41 UTC
