### ISSUE TITLE
Please add option to pause the current video if another video is played

### ISSUE THREAD

**Issue by jithinrajiv** [sampotts/plyr#624] opened 2017-07-27 18:48 UTC
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
-

**Comment by friday** [comment] 2018-05-25 03:41
Duplicate of #144

**Closed by friday** 2018-05-25 03:41 UTC
