### ISSUE TITLE
local video has poster volume bar be hidden

### ISSUE THREAD

**Issue by louie-senpai** [sampotts/plyr#1219] opened 2018-10-17 08:39 UTC
<img width="535" alt="wx20181017-163742 2x" src="https://user-images.githubusercontent.com/23182715/47073514-0559d480-d22b-11e8-8e0e-a59a29539a99.png">

in mac chrome  v70.0.3538.67

**Comment by sampotts** [comment] 2018-10-24 13:06
What version of the library?

**Comment by louie-senpai** [comment] 2018-11-03 16:08
@sampotts Yes,is latest.

**Comment by nmedias** [comment] 2018-11-08 16:07
Same here. Mac/Chrome 70.0.3538.77

**Comment by Temperament** [comment] 2018-11-23 22:53
Same here. Chrome.

**Comment by sampotts** [comment] 2018-11-24 01:35
Feel free to take a look and open a pull request 👍

**Comment by benwick** [comment] 2018-12-04 09:58
The same with Chrome 70.0.3538.110 on Windows...

**Comment by Maqsyo** [comment] 2018-12-04 09:59
Same here ♥

**Comment by benjasHu** [comment] 2019-02-27 12:59
Same here

**Comment by potskhveria** [comment] 2019-05-22 03:16
Same here

**Comment by rmamchyk** [comment] 2019-06-24 20:58
Some here Mac/Chrome 75.0.3770.100

**Comment by tylerrowsell** [comment] 2019-07-12 15:17
I'm experiencing the same thing. A hidden tag is being added to them. Not sure where it comes from.
![https://screenshot.click/12-16-7dinb-7jxi2.png](https://screenshot.click/12-16-7dinb-7jxi2.png)

It is removed when I scrub on the progress bar though.

**Comment by zethodderskov** [comment] 2019-07-14 17:02
Same here

**Comment by sampotts** [comment] 2019-07-15 03:39
Happy to review PRs for this - they're a lot useful than "same here"s 👍 😉. 

The problem is that the inverse was originally an issue; a video with *no* audio showed the volume control. Some logic was added to hide the volume control if no audio track was present. The problem is the browser seems to give flaky results when querying for an audio track. You'll see that there's several events that we check for audio but perhaps we need to add more in there for make up for the crappy browser APIs 🤦‍♂️

**Comment by JeroPizarro** [comment] 2019-08-05 14:55
Hey guys, if you put the preload attribute on your video tag, volume bar appears.

`<video preload="none">`

It's not a fix but maybe help someone.

**Comment by Shaker-Hamdi** [comment] 2019-09-29 09:23
Same issue here as well.

**Comment by sihhanwang** [comment] 2019-10-18 04:35
Same issue here as well.
`<video preload="none">` 
not works for me

**Comment by kfeng0806** [comment] 2019-10-27 10:19
```javascript
player.once('canplay', () => player.currentTime = 0);
```

**Comment by mayeaux** [comment] 2020-01-26 16:10
@sampotts I understand the logic behind the original functionality, but now that we know the browser APIs are sketchy can we just reverse it until we can figure out a more stable way to hide the volume when there's no audio track? I think not having a volume button on a video with sound is more broken than a volume button appearing on a video with no sound, that's my two cents curious to hear your take.

**Comment by mayeaux** [comment] 2020-04-06 00:58
Was this ever fixed? This is really broken for me, not being able to change the sound on a video with sound is terrible UX, is this fixed in a newer version or what's the latest version before the change was implemented that caused this? 🤔

**Comment by sampotts** [comment] 2020-04-06 01:13
Yes, the logic to hide the volume control has been reverted due to the browser APIs not working as expected. Yes, it's not great UX but it was temperamental behavior and hard to reproduce. If you want to hide the volume control now, you have to do so via the `controls` option.

**Closed by sampotts** 2020-04-06 01:13 UTC

**Comment by sampotts** [comment] 2020-04-06 01:14
See the changelog for v3.5.7:
https://github.com/sampotts/plyr/blob/master/changelog.md#v357

**Comment by mayeaux** [comment] 2020-04-06 01:17
Hey np at all, I know browsers can be finicky, overall plyr is great thank you for your work!
