### ISSUE TITLE
[V3] [3.0.2] IE11 doesn't hide the play button when "clickToPlay" is true and the video has ended

### ISSUE THREAD

**Issue by MBWebTechMariusz** [sampotts/plyr#824] opened 2018-03-20 20:07 UTC
### Expected behaviour
After the video has ended and the user clicks _not_ on the play button, but on the video while "clickToPlay" is active, the video should start and the play button + controls should hide.

### Actual behaviour
The video starts, but the play button is not hidden.
**Remark**: When clicking on the play button, the play button disappears as expected.

### Environment

- Browser: IE
- Version: 11
- Operating System: Windows
- Version: 8.1

### Steps to reproduce
Only works on IE11 on my site; see the "expected behaviour.

### Further investigation
It seems that in IE11, when the video is ended and the following code is being executed (around line 9442):
```
                        } else if (_this3.player.ended) {
                            _this3.player.restart();
                            _this3.player.play();
                        }
```
the player is not triggering the "play" event somehow.

I checked the code when the play button is being clicked, and if I remove the restart(), it works, but I don't know why.
Proposed fix:
```
                        } else if (_this3.player.ended) {
                            if (!browser$1.isIE) {
                                _this3.player.restart();
                            }
                            _this3.player.play();
                        }
```

**Comment by friday** [comment] 2018-05-28 01:10
I think this should be fixed by now (v3.3.9). I can't reproduce the issue on the demo, which has `clickToPlay`

**Closed** 2018-05-30 00:49 UTC
