### ISSUE TITLE
Plyr video VR

### ISSUE THREAD

**Issue by nvybvl** [sampotts/plyr#803] opened 2018-03-08 09:23 UTC
- [x ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
I want to play VR videos on Plyr

### Actual behaviour
I want to play VR videos on Plyr

### Environment

- Browser: Chrome, Safari, FireFox, Edge
- Version:  Latest
- Operating System: MacOS, Windows
- Version: Latest

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
I want to play VR videos on Plyr

**Comment by friday** [comment] 2018-05-25 00:50
Duplicate of #628

**Closed by friday** 2018-05-25 00:50 UTC
