### ISSUE TITLE
Failing to integrate plyr into a simple ionic2 app

### ISSUE THREAD

**Issue by AlGantori** [sampotts/plyr#432] opened 2016-11-28 06:56 UTC
Hi, I am having really hard time integrating plyr into a relatively simple ionic2 app
here is the plunker
http://plnkr.co/edit/RtwseYFzBl77IVK3qtTv?p=preview

I think I need only one instance of plyr to play any youtube movie from my various playlists. IOW, I should not have to destroy an instance and have to create another one later for a different playback.

I would like to be able to feed the next movie (one at a time) upon trapping event "ended" because a playlist may have mixed media (other players)

From a media selector view, I am trying to navigate to the plyr page and retrieve perhaps a global instance and tell it to play a movie, the user may back out from this popup and return to a media selector/list anytime.

The plyr loads on the first visit by clicking button "SHOW PLAYER PLYR" but not on subsequent clicks.  What am I doing wrong?
Perhaps PlyrView.html where plyr is getting setup is getting destroyed and we have to call plyr setup again?  Can this re-loading be avoided?

Also while the v1.8.12 loads OK in this plunker, I tried to moving to v2.0.10 and now v2.0.11 but I get all kinds of exceptions like

> EXCEPTION: TypeError: Cannot read property 'match' of null
> Uncaught ReferenceError: ytcfg is not defined (I think this one is YouTube API document problem)
> 

I would really appreciate it if you can upgrade this plunker to v2.0.11
Thank you.

**Comment by bartman110** [comment] 2016-11-28 21:08
I also have EXCEPTION: TypeError: Cannot read property 'match' of null since I updated plyr to the latest.

**Comment by AlGantori** [comment] 2016-11-28 22:10
I have made some edits to the plunker above since the original post (oops) and the behavior is better.
http://plnkr.co/edit/RtwseYFzBl77IVK3qtTv?p=preview

I now call plyr.setup() upon the plyrView.ts onPageLoaded() 
Also I have introduced a boolean "attached" in PlyrService.ts in order to avoid registering plyr events multiple times (without having to use jQuery there is no elegant way in JS to do this apparently).

Good/Bad news: The plyr is now loading OK every time we navigated to the page it is hosted in PlyrView.html, however the video is not playing upon event "ready" firing.  It think there is something going in the plunker like a race condition because it is basically identical to my development code which does not exhibit this last issue.

If a JS guru/native out there would like to help me, please look at PlyrView.ts and PlyrService.ts
Thank you.

**Comment by SamPotts** [comment] 2016-11-28 22:12
Couple of issues here. I'm not familiar with ionic so not sure how much help I can be there. 

The exception with 'match' on null means the embed id is not set for whatever reason. Do you have any code examples? Do you see this error on https://plyr.io?

**Comment by SamPotts** [comment] 2016-11-28 22:14
Also the `Uncaught ReferenceError: ytcfg is not defined(…)` is from YouTube unfortunately. Their API and Vimeo's are a bit flaky at best.

**Comment by AlGantori** [comment] 2016-11-29 01:55
I have forked the original plunker into http://plnkr.co/edit/2vChA10IchkL53DWDV0v?p=preview  for v2.0.11
Basically, I adjusted 

- index.html to reference v2.0.11

- PlyrService.ts  to pick the 1st player from the returned array of players and using Player.on() to register the desired events once.

```
Setup() {
    console.log("PlyrService.Setup...");
    // register all plyr events only *once* (without jQuery, a boolean is one way)
    if (!attached) {
      // -- Notify me when this plyr player is setup, so I can wire the needed plyr events
      document.addEventListener('setup', () => {
        console.log("video SETUP");
        PlayerElement = document.querySelectorAll('#js-plyr')[0];
        // this.Player = plyr.setup()[0].plyr;
        // -- wire needed events
        this.WireDesiredEvents();
      });
    }
    attached = true;
    // plyr API expect us to call .setup() on the player HTML element
    // plyr.setup(PlayerElement)[0];  // NOTE: on a single instance, .plyr returns false ???

    // this.Player = plyr.setup()[0].plyr; // v1.8.12
    this.Player = plyr.setup('#js-plyr')[0]; // v2.0.11 (pick 1st and only player)
    Player_GlobalInstance = this.Player;
  }
```

Does the above Setup() flow make sense ? :)
I am not seeing the 'match' exception in this plunker unlike from vscode IDE, however it seems plyr.setup fails and returns "undefined",  I don't see it return an indication of this on the console, it would be nice if did.

I think even though the edits above to move from v1.8.12 to v2.0.11 are not much the element hosting plyr is perhaps ?now? not getting loaded in time for plyr.setup.

I will keep hacking, no other choice :(

**Comment by AlGantori** [comment] 2016-12-05 04:46
I am moving away from the idea of navigating to a page containing the plyr player because, navigating out of the page destroys the page and thus plyr (at least that's my current understanding, unless you can keep a plyr HTML element in the ether and moving into another page at a later point).
Hosting all my players (plyr and custom) inside a single ionic tab and managing their exclusive visibility is my next approach to keep them all around.  If you think there is a better way, let me know
I will be closing this for now.

A note to the awesome author(s) of plyr, Hi Sam!, I wish you could maintain a simplified sample of plyr which demonstrate via "simple JS code" some of the major functionality and code patterns you would like to follow.

I find the main sample you point to  https://plyr.io way too complex to wrap my head around it.

I was thinking something (ugly) like this:
https://www.w3.org/2010/05/video/mediaevents.html 

I did use this to verify that volume is now expressed from 0 to 1 both in reading and setting it (the doc for your setVolume I think is behind and confused me saying 0 to 10).   Also I am not sure if the "HTML5 video events" are the exact same thing as your plyr?

A plyr TESTER one page app, could perform the following behind dedicated buttons:
1) setup of plyr
2) destruction of plyr (I personally don't plan on this rather I need to load the next media explicitly when the previous one ends, this allows me to control the sequencing, perhaps in between media prompts,  implement end-of-playlist in order to jump to a different one, ...)
3) how to properly register events  once (setup, ready, play, ended, ...)  are they guarantied to happen?
4) what does the "event" argument provide for each of the events, (where to look up this information)
Can event arg provide access to volume property or I have to use GetVolume? (which I am now).
5) how to un-register events 

the following would be extra
6) provide various media list of (short) test media eg. A) YouTube only, B) Vimeo ony, C) audio?, D) a mix
7) Let's stop here

You can use for-each but keep the instances of plyr to one for simplicity.
Such a sample of active code page would assist you as well as us developer, 
1) verify and confirm the behavior of plyr with each revision.
2) gain understanding of the sequence of events

I do keep a rudimentary sample as I am a poor JS coder :(, (too late to fix), ideally I would want the console output to be integrated but the browser console is fine to see the events, property values, etc... log.
Let me know if you would like me to email it to you, it will certainly provide a good chuckle :)
Thank you.

**Comment by AlGantori** [comment] 2017-02-05 19:37
Hello, regarding the "cannot read property match", here is some output from the console.
I tried latest 2.0.11 and I get the same thing.
Let me know what else I could capture for you.
```
PlyrService------------>>Created
PlyrPlayerComp.ts:34PlyrPlayerComp------------>>Created
PlyrPlayerComp.ts:43PlyrPlayerComp------------>>ngOnInit
PlyrService.ts:113PlyrService.Setup...
error_handler.js:47EXCEPTION: Error in :0:0 caused by: Cannot read property 'match' of nullErrorHandler.handleError @ error_handler.js:47IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:49ORIGINAL EXCEPTION: Cannot read property 'match' of nullErrorHandler.handleError @ error_handler.js:49IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:52ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:52IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:53TypeError: Cannot read property 'match' of null
    at T (https://cdn.plyr.io/2.0.11/plyr.js:1:4512)
    at re (https://cdn.plyr.io/2.0.11/plyr.js:1:17133)
    at ne (https://cdn.plyr.io/2.0.11/plyr.js:1:17007)
    at He (https://cdn.plyr.io/2.0.11/plyr.js:2:3344)
    at new E (https://cdn.plyr.io/2.0.11/plyr.js:2:4884)
    at https://cdn.plyr.io/2.0.11/plyr.js:2:6363
    at Array.forEach (native)
    at Object.A [as setup] (https://cdn.plyr.io/2.0.11/plyr.js:2:6184)
    at PlyrService.Setup (http://localhost:8100/build/main.js:15698:28)
    at PlyrPlayerComp.ngOnInit (http://localhost:8100/build/main.js:58229:26)ErrorHandler.handleError @ error_handler.js:53IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:56ERROR CONTEXT:ErrorHandler.handleError @ error_handler.js:56IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:57DebugContext {_view: C…e.proxyViewClass, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}ErrorHandler.handleError @ error_handler.js:57IonicErrorHandler.handleError @ ionic-error-handler.js:56(anonymous function) @ application_ref.js:210t.invoke @ polyfills.js:3onInvoke @ ng_zone.js:236t.invoke @ polyfills.js:3e.run @ polyfills.js:3(anonymous function) @ polyfills.js:3t.invokeTask @ polyfills.js:3onInvokeTask @ ng_zone.js:227t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
PlyrPlayerComp.ts:34PlyrPlayerComp------------>>Created
PlyrPlayerComp.ts:43PlyrPlayerComp------------>>ngOnInit
PlyrService.ts:113PlyrService.Setup...
error_handler.js:47EXCEPTION: Error in :0:0 caused by: Cannot read property 'match' of nullErrorHandler.handleError @ error_handler.js:47IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:49ORIGINAL EXCEPTION: Cannot read property 'match' of nullErrorHandler.handleError @ error_handler.js:49IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:52ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:52IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:53TypeError: Cannot read property 'match' of null
    at T (https://cdn.plyr.io/2.0.11/plyr.js:1:4512)
    at re (https://cdn.plyr.io/2.0.11/plyr.js:1:17133)
    at ne (https://cdn.plyr.io/2.0.11/plyr.js:1:17007)
    at He (https://cdn.plyr.io/2.0.11/plyr.js:2:3344)
    at new E (https://cdn.plyr.io/2.0.11/plyr.js:2:4884)
    at https://cdn.plyr.io/2.0.11/plyr.js:2:6363
    at Array.forEach (native)
    at Object.A [as setup] (https://cdn.plyr.io/2.0.11/plyr.js:2:6184)
    at PlyrService.Setup (http://localhost:8100/build/main.js:15698:28)
    at PlyrPlayerComp.ngOnInit (http://localhost:8100/build/main.js:58229:26)ErrorHandler.handleError @ error_handler.js:53IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:56ERROR CONTEXT:ErrorHandler.handleError @ error_handler.js:56IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
error_handler.js:57DebugContext {_view: C…e.proxyViewClass, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}ErrorHandler.handleError @ error_handler.js:57IonicErrorHandler.handleError @ ionic-error-handler.js:56next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3i @ polyfills.js:3
polyfills.js:3 Unhandled Promise rejection: Error in :0:0 caused by: Cannot read property 'match' of null ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in :0:0 caused by: Cannot read property 'match' of null
    at ViewWrappedError.BaseErr…, originalError: TypeError: Cannot read property 'match' of null
    at T (https://cdn.plyr.io/2.0.11/plyr.js:1:4512)…, context: DebugContext} TypeError: Cannot read property 'match' of null
    at T (https://cdn.plyr.io/2.0.11/plyr.js:1:4512)
    at re (https://cdn.plyr.io/2.0.11/plyr.js:1:17133)
    at ne (https://cdn.plyr.io/2.0.11/plyr.js:1:17007)
    at He (https://cdn.plyr.io/2.0.11/plyr.js:2:3344)
    at new E (https://cdn.plyr.io/2.0.11/plyr.js:2:4884)
    at https://cdn.plyr.io/2.0.11/plyr.js:2:6363
    at Array.forEach (native)
    at Object.A [as setup] (https://cdn.plyr.io/2.0.11/plyr.js:2:6184)
    at PlyrService.Setup (http://localhost:8100/build/main.js:15698:28)
    at PlyrPlayerComp.ngOnInit (http://localhost:8100/build/main.js:58229:26)o @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'match' of null(…)o @ polyfills.js:3r @ polyfills.js:3i @ polyfills.js:3
```

**Comment by friday** [comment] 2018-05-17 03:28
I'm closing this since this it's over a year and there's nothing anyone could help with or respond to it at this point.

If you ask at [our slack](https://bit.ly/plyr-chat) with a code playground (like http://plnkr.co), the latest Plyr version and minimal code to reproduce your problem I will try to help you.

**Closed by friday** 2018-05-17 03:28 UTC

**Comment by AlGantori** [comment] 2018-05-17 07:37
Yes, of course forgot to come by here.  I basically remained on v1.8.12, until recently 20180412, where it too was no longer working.  I gave a try to v3.1.0 and it worked without complaints :)
Thanks.
