### ISSUE TITLE
auto play doesn't work in Android , iPhone Browser 

### ISSUE THREAD

**Issue by paveltech** [sampotts/plyr#767] opened 2018-01-27 19:01 UTC
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
 Auto play in android /iOS browser
### Environment
Android / iOS

- Browser: Android / iOS Browser 
- Version:  2.0.18
- Operating System: Marshmallow 6.0.1 
- Version: 

Players affected:
- [ ] Android Browser 

### Steps to reproduce 
-

**Comment by friday** [comment] 2018-01-27 20:14
Duplicate of #716 most likely. This is how HTML video behaves in mobile browsers.  https://github.com/sampotts/plyr/issues/716#issuecomment-345351316

**Comment by sampotts** [comment] 2018-01-30 02:07
Autoplay on is only supported if the video either has no audio tracks or has the `muted` attribute on a mobile device (rightfully so, as most of the time it's a pain in the arse). This isn't something I have control over but is a browser decision.

**Closed by sampotts** 2018-01-30 02:07 UTC
