### ISSUE TITLE
YouTube + Android Chrome: setting speed doesn't affect real speed

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#860] opened 2018-04-03 06:50 UTC
### How to reproduce: 
1. Open demo video on Android Chrome: https://plyr.io/#youtube
2. Try to set any other speed than normal

### Environment
- Browser: Android Chrome
- Version: 65.0.3325.109
- Operating System: Android
- Version: 7.0 NRD90M

**Comment by sampotts** [comment] 2018-04-03 06:51
Isn't this a duplicate of your other issue?

**Comment by yuriykuzin** [comment] 2018-04-03 06:54
@sampotts Not, it is a different one. Here UI works properly and shows different selected values, but the speed remains the same.

**Comment by sampotts** [comment] 2018-04-03 12:32
Ahh ok cool 👍 I've found the cause and both are related. Will push it to master shortly.

**Comment by sampotts** [comment] 2018-04-03 13:01
This is fixed in `v3.1.0`

**Closed by sampotts** 2018-04-03 13:01 UTC
