### ISSUE TITLE
Plyr is merging into Vidstack

### ISSUE THREAD

**Issue by sampotts** [sampotts/plyr#2408] opened 2022-01-24 10:25 UTC
See https://github.com/sampotts/plyr/issues/2737 for update.

**Comment by mihar-22** [comment] 2022-01-24 10:56
Super excited as we've been working on `@vidstack/player` for a while now, and I've been looking forward to sharing it with the Plyr community. 

Two more things I want to add quickly is:

1. `@vidstack/player` is currently being used at Reddit on their new mobile web platform! New UI we've been putting together at Reddit should be released sometime next week.

2. Working on getting the issues related to the Beta release up. You can more information [here](https://github.com/vidstack/player/issues/580). Just note that we're still actively working on it, so consider it a WIP.

**Comment by sparkktv** [comment] 2022-01-26 20:16
A few questions, will it work the same way as Plyr?
Will there be YouTube & Vimeo support still?
And can we continue to use Plyr if we choose for the foreseeable future?

**Comment by mihar-22** [comment] 2022-01-26 22:54
Hey @sparkktv 😄 

> Will it work the same way as Plyr?

I'm not entirely sure what you're hoping will be the same when you ask this (if you could elaborate on some features), but what I can say is we're planning on creating a legacy Plyr skin. This means you'll get the exacts same look and feel, with mostly the same configuration options. All you need to do from your end is install a new package, and update a few lines of HTML.

> Will there be YouTube & Vimeo support still?

Yes! That's planned for the 1.0 release.

> And can we continue to use Plyr if we choose for the foreseeable future?

Yes! Even after we archive Plyr it'll still be available via NPM/CDN, but the next major version will be deprecated. All this means is as long as you're version locked, you can stay on Plyr as long as you like, it just won't be receiving any updates.

Hope that helps!

**Comment by adeeb1** [comment] 2022-01-29 06:00
1. Will features that are already production-ready like [Dailymotion support](https://github.com/sampotts/plyr/pull/2136) and [markers](https://github.com/sampotts/plyr/pull/2386) be included?
2. What's the timeline for 1.0 release?

**Comment by sampotts** [comment] 2022-01-29 06:05
> * Will features that are already production-ready like [Dailymotion support](https://github.com/sampotts/plyr/pull/2136) and [markers](https://github.com/sampotts/plyr/pull/2386) be included?

Those features may well be production-ready for Plyr, but they won't be able to be directly ported over to the Vidstack player. It's a complete re-write from the ground up, using web components. Some of the code/logic from those changes will be able to be carried over but the thought is that Vidstack will offer a plugin framework unlike Plyr where you get all or nothing. 

> * What's the timeline for 1.0 release?

Rahim can correct me if I'm wrong but we've not discussed a firm date. This is an open source project and Rahim and I both have full time jobs. We're committing as much time as we can to get it over the line.

**Comment by lofcz** [comment] 2022-02-07 02:14
@sampotts would you please consider merging #2386 and #2410 upstream? While we understand you are now focusing on Vidstack there is and _will be_ a huge community around Plyr for a long time.

**Comment by sampotts** [comment] 2022-02-07 03:48
> @sampotts would you please consider merging #2386 and #2410 upstream? While we understand you are now focusing on Vidstack there is and _will be_ a huge community around Plyr for a long time.

Sure, I'll take a look this week.

**Comment by gaminglnk** [comment] 2022-02-11 06:38
@sampotts Most importantly will you please provide option to change quality of an MPEG DASH or HLS stream while it's playing.
 Just like streaming site like youtube in which we are able to change the video resolution/quality while the video is playing.

**Comment by spmeesseman** [comment] 2022-03-02 17:55
Hi Sam first off thank you so much for the great work with plyr.  I tried emailing you about this but will the new Vidstack project have any commercially supported licenses available?  I had sent an email asking about a commercial license for plyr at a cost (my company is forcing removal of all open source from our projects) which would be ideal, but just wondering if we can discuss that maybe over email?

**Comment by sampotts** [comment] 2022-03-02 21:37
Sorry Scott, I’ll get back to you today. 

Cheers
Sam

**Comment by fredlunau** [comment] 2022-03-05 16:34
I just started using plyr a few months ago (along with glightbox and losslesscut) to slowly build a way to view video clips from within my larger (and way longer) otherwise boring home videos.  Thanks for a fabulous library that even me, a weekend JS developer at best, can enjoy using!

**Comment by spmeesseman** [comment] 2022-03-08 15:05
Hi again Sam, just wanted to make sure you were able to locate my email and can replay when you have a chance, my company is all over me to see if we can work something out.  I'd love to get something worked out and you paid at the same time for all your great work.  If we can't work something out they want me to remove plyr (long story I can explain if needed once we chat) and that would ****.

**Comment by mihar-22** [comment] 2022-03-10 05:00
👋 

The Vidstack Player Beta is here: https://github.com/vidstack/player/discussions/626

Enjoy!

**Comment by ffxsam** [comment] 2022-07-05 17:17
Should we be using Vidstack now that it's at version 1.6.1? The only thing I'm confused about is that the docs seem to be for 0.x, and there's no documentation on how to use the player with Vimeo or YouTube.

**Comment by mihar-22** [comment] 2022-07-05 22:50
> Should we be using Vidstack now that it's at version 1.6.1?

Sorry for the confusion @ffxsam, the version `1.6.1` is currently on the `@next` tag. I'll update the docs to reflect that's `next` instead of `0.x` (semantically the same thing). We're still actively working on it and wouldn't consider it production ready for the public, so for now my recommendation is to keep using Plyr.

> The only thing I'm confused about is that the docs seem to be for 0.x, and there's no documentation on how to use the player with Vimeo or YouTube.

There's links for [Vimeo](https://www.vidstack.io/docs/player/components/providers/vimeo/)/[YouTube](https://www.vidstack.io/docs/player/components/providers/youtube/) because we get asked that a lot. It's right under the "Providers" section. If you follow the links you'll see that it's on the roadmap :)

**Comment by ffxsam** [comment] 2022-07-07 00:20
@mihar-22 Thanks a ton! (and for all your work on Vidstack - can't wait till it's production-ready!)

**Comment by davidtrattnig** [comment] 2022-08-23 18:02
@mihar-22 two questions:

1.) Does Vidstack also support audio-only use? Not only technically but is it also providing a nice audio player UI, not just a video player UX able to play audio files too? Would be great if there are some demo pages or screen shots for that use case.

2.) Since it appears that you plan to monetize Vidstack, will the basic features always stay free? Where do you plan to draw the line?

Since I'm currently researching a versatile player for radio stations, these topics are essential too me.

**Comment by mihar-22** [comment] 2022-08-23 23:41
Hey @davidtrattnig!

1) Yes we will support audio as much as possible including a neat default UI. We will be adding things to the home page over time such as features, skins and so on as we complete them.

2) The player and other open-source projects will always be free and have more than enough features for most people to build what they need. Anything paid will be created to save you additional time such as media UI templates, possibly some additional skins (beyond the default), our CMS and so on. We look up to companies such as Laravel and hope to provide the same balance.

Feel free @davidtrattnig and anyone else to come over to the [Discord Channel](https://discord.com/invite/7RGU7wvsu9) if you have any further questions.

**Comment by davidtrattnig** [comment] 2022-08-24 06:57
@mihar-22 Many thanks for your quick and detailed answer!

**Comment by ljfreelancer88** [comment] 2022-09-19 19:35
Are you planning to add also a feature where I can be able loop "section" of a video? Say I want to loop a video starting from 4sec. to 8sec. and repeat the loop to (n) times. This use case is for musicians alike who transcribe songs.

**Comment by h57758** [comment] 2022-10-08 14:24
Vidstack is one of the most ugly video players out there, firefox's default styling for video elements looks better than vidstack

**Comment by h57758** [comment] 2022-10-08 14:25
And that Plyr skin will have to be the default, otherwise I will use Plyr even if you want me to or not

**Comment by h57758** [comment] 2022-10-08 14:27
Why monetize it? You really do want me to use Plyr instead of Vidstack. And even if you were to give Vidstack a nice interface I would never contribute a single thing to it, because you are making it proprietary.

**Comment by h57758** [comment] 2022-10-08 14:28
I'd literally rather use Video.JS (Which used to be the ugliest video player) instead of Vidstack.

**Comment by h57758** [comment] 2022-10-08 14:31
And why did you darken the video when you hover the video in Vidsack, Vidstack and your UI design for Vidsack are both horrible.

**Comment by mihar-22** [comment] 2022-10-08 22:02
You’re special @h57758. That’s not our default skin, it’s simply a demo to showcase some of the controls and features while we’re working on things in the background. You’d know if you asked.

Vidstack player is MIT licensed. Not sure what your proprietary spiel is about.

**Comment by h57758** [comment] 2022-10-08 22:06
1. Ok! But why don't you show the default skin on the demo (Maybe it isn't finished?)
2. Ignore what I said on that one.

Sorry for not asking, but why would I, people would showcase exactly what they are offering on the webpage. (Btw, it is the middle of the night 00:06)

**Comment by lofcz** [comment] 2022-10-09 02:08
@mihar-22 takes some self-control to write a reply like that one 👍🏻

**Comment by ffxsam** [comment] 2022-10-09 21:06
@h57758 Many people contributing to this project are doing so for free. Please take some consideration before posting rude and unconstructive comments about people's hard work.

Plus, if you really dislike some of the design decisions, you're welcome to fork the repo and create your own build.

**Comment by h57758** [comment] 2022-10-10 10:56
> @h57758 Many people contributing to this project are doing so for free. Please take some consideration before posting rude and unconstructive comments about people's hard work.
> 
> 
> 
> Plus, if you really dislike some of the design decisions, you're welcome to fork the repo and create your own build.

1. Sorry
2. I'm not a designer and I will never be able to top Plyr's interface.

**Comment by ottman** [comment] 2023-01-25 17:12
What is the status on this @sampotts ?

**Comment by mihar-22** [comment] 2023-01-25 23:13
## Status Update

- We spent a good portion of last year building tooling to help us ship a media player that meets our design goals. Recap can be found in our [first major release this year](https://github.com/vidstack/player/discussions/716). This release also includes heaps of QOL improvements such as out of the box styles to get up and running quickly.
- This week we followed up that release with React 18 and Next.js support including SSR -> [release notes](https://github.com/vidstack/player/discussions/722).
- We have our [community skin designs up on GitHub](https://github.com/vidstack/player/discussions/702). Make sure to scroll through, there's heaps of examples.

## What's Next?

 For the coming week we're working on additional small fixes, wrapping up the docs, and releasing our [media icons set](https://twitter.com/billygozutok/status/1574270573013704704).

 Following that all we have left is reaching feature parity which includes the tasks on this [project board](https://github.com/vidstack/player/projects/1). It looks roughly about a sprint worth of work (<2 weeks). Right after that it's just skins, putting together examples, and getting ready to ship 1.0. Rough estimate at this time looks like end of March to completion but don't hold me to it because we still have to figure out funding and other stuff which might eat some time.

## Screenshots

![](https://cdn.discordapp.com/attachments/923396209425670154/1065154163266306048/image.png)


![](https://user-images.githubusercontent.com/55968580/204430334-2dcb16d5-b348-47f4-8d53-d394d52455e4.png)


![](https://user-images.githubusercontent.com/55968580/205538233-76a1f576-16f4-481f-b053-6716d7ced224.png)

**Comment by benderillo** [comment] 2023-02-05 10:59
Question: since Plyr is merging into vidstack, are the issues submitted to Plyr repo no longer addressed?

**Comment by sampotts** [comment] 2023-02-05 11:03
Major bugs will be for sure. The space bar issue you've opened has been addressed in a PR, I just need to merge (if I've not already) and release it to npm. 

I've not had much time to work on Plyr or Vidstack (just had another kid), but I'm hoping I can create a Plyr-like skin for the Vidstack player so folks have the same UI that seems to be a popular feature. I don't see Plyr going anywhere anytime soon.

**Comment by benderillo** [comment] 2023-02-05 11:06
> Major bugs will be for sure. The space bar issue you've opened has been addressed in a PR, I just need to merge (if I've not already) and release it to npm.
> 
> I've not had much time to work on Plyr or Vidstack (just had another kid), but I'm hoping I can create a Plyr-like skin for the Vidstack player so folks have the same UI that seems to be a popular feature. I don't see Plyr going anywhere anytime soon.

Congrats on a new kid!!!  
Could you share a PR number to have a look at the fix please :)

**Comment by sampotts** [comment] 2023-02-05 11:07
Thanks! 

I _think_ [this PR](https://github.com/sampotts/plyr/pull/2581) should fix your issue. I'll try and get a release out in a day or two. Sorry, I'm so slow.

**Comment by benderillo** [comment] 2023-02-05 15:18
> I think https://github.com/sampotts/plyr/pull/2581 should fix your issue. I'll try and get a release out in a day or two. Sorry, I'm so slow.

@sampotts Much appreciated!

**Comment by connecteev** [comment] 2023-08-25 05:07
@mihar-22 @sampotts When can we expect vidstack to have a vue version available? Plyr and Vime (both of which are merging into vidstack) have vue bindings, but I don't see anything like that for vidstack. Thanks...

**Comment by mihar-22** [comment] 2023-08-25 06:06
We'll have Vue install docs very soon, but you'll need to use our Web Component library. Vue has perfect support for it, so you won't be missing out anything special. The pre-1.0 is coming in 1-2 weeks (depending on how long new docs take) which is where I'll strongly recommend migrating over. I'll have more information as soon as the release is out.

**Comment by connecteev** [comment] 2023-08-26 11:31
@mihar-22 sounds great, can't wait for this to be out.

**Comment by dohahelmy** [comment] 2023-09-10 02:21
@mihar-22 Any update soon for the VUE docs?

**Comment by mihar-22** [comment] 2023-09-10 04:18
I'm working on our new docs as we speak. We have a completely new site and player library dropping very soon, feeling confident it should be in a week or two latest. It's been a long 2+ months of work on this so really looking forward to sharing it! Just a little bit more time needed to wrap it all up.

**Comment by ffxsam** [comment] 2023-09-12 15:55
@mihar-22 You and the team are doing awesome work! Can't wait to implement the new Vidstack into our platform.

**Comment by kasvith** [comment] 2023-09-27 22:50
Hi, will Vimeo support quality control(for paid accounts)?

**Comment by mihar-22** [comment] 2023-10-08 05:33
Closing this issue now as we have an update here: https://github.com/sampotts/plyr/issues/2737

**Closed by mihar-22** 2023-10-08 05:33 UTC

**Comment by kgnfth** [comment] 2024-05-02 19:45
I dont like it. Plyr is easy to use and simple to setup. Everything in vidstack is difficult to setup for me.

**Comment by mihar-22** [comment] 2024-05-03 02:37
Feel free to drop by and share what's difficult. If you like the current Plyr setup, what's different or difficult about this?

```ts
import { VidstackPlayer, PlyrLayout } from 'vidstack/global/player';

const player = await VidstackPlayer.create({
  target: '#target',
  title: 'Sprite Fight',
  src: 'https://files.vidstack.io/sprite-fight/720p.mp4',
  poster: 'https://files.vidstack.io/sprite-fight/poster.webp',
  layout: new PlyrLayout({
    thumbnails: 'https://files.vidstack.io/sprite-fight/thumbnails.vtt',
  }),
});
```

By the way, we also have Plyr compatability:

```ts
import { Plyr } from 'vidstack/global/plyr';

const player = new Plyr('#target', {
  title: 'Sprite Fight',
  src: 'https://files.vidstack.io/sprite-fight/720p.mp4',
  poster: 'https://files.vidstack.io/sprite-fight/poster.webp',
  thumbnails: 'https://files.vidstack.io/sprite-fight/thumbnails.vtt',
});
```

I'd argue the Web Components and React libraries are even easier. All setup is available in our [installation docs](https://www.vidstack.io/docs/wc/player/getting-started/installation?styling=default-layout&provider=video).

**Comment by deedarb** [comment] 2024-05-03 05:40
I migrated from Plyr to vidstack and found out that vidstack is not working in Android 8.1 inside ionic application, reverted back to Plyr and planning to migrate to video.js 😮‍💨

**Comment by mihar-22** [comment] 2024-05-03 06:32
Not much we can do if bugs are not reported. You'll inevitably find an issue with every player, it's on you to help the maintainers find and fix the bug, it's a natural part of adopting open-source.

**Comment by deedarb** [comment] 2024-05-03 09:31
it is not a bug/error, old web views do not support custom elements. https://www.vidstack.io/docs/player/getting-started/installation/javascript?provider=video&styling=default-layout&install=npm#5-check-support
Some users have old phones or do not update system webview.

**Comment by hdhub4ufile** [comment] 2024-09-26 08:27
[https://file-to-link-nx-b8f69ee9ae53.herokuapp.com/watch/66f51ac0c1a7b282daf76465](url)

**Comment by Yashavanth07** [comment] 2025-03-06 07:06
I am currently using Plyr.io. Since Plyr is merging into Vidstack, should I switch now, or is there an official deprecation timeline for Plyr?"

**Comment by jimmywarting** [comment] 2025-07-14 16:09
While I appreciate the effort and ambition behind Vidstack, I must admit I’m disappointed by the shift away from Plyr's original philosophy. What made Plyr great for me — and many others — was its clean, dependency-free, vanilla JavaScript approach. It was lightweight, framework-agnostic, and easy to drop into any environment without worrying about build systems or tight coupling to a specific stack.

With Vidstack now embracing TypeScript, Web Components, and integrations with React, Vue, Svelte, etc., it feels significantly more opinionated and complex. I understand this might benefit some modern app ecosystems — but for many of us working outside those ecosystems, it's a real burden.

The need to pull in a full framework just to use a media player — or worse, to align it with another framework we already use — adds unwanted overhead, compatibility concerns, and increases bundle sizes. I don't want to load my own framework (vue, lit.js svelt, react or whatever) and your system and possibly reconcile that with my own setup. i did quite like that plyr was just html css and js.

To be fair, I haven’t looked deeply into Vidstack yet, and I’m sure it has its strengths. But honestly, I’m just not excited to try it. If Plyr is truly abandoned, I’d probably lean toward something like Video.js or MediaElement.js instead.

I really wish someone would pick up the torch and continue Plyr’s original vision — a simple, modern, framework-free media player that “just works”

guess i will say god bye to both plyr and vidstack and look for something else if this is going to be discontinued.

**Comment by mrleblanc101** [comment] 2025-07-14 16:19
@jimmywarting WebComponents do not require you to use a framework, do they ? 🤔

**Comment by mrleblanc101** [comment] 2025-07-14 18:22
> either way here is the crux: vidstack use maverick. i might use svelte. now i'm using two frontend frameworks (maverick - aka react? and svelte) - don't want that.

Just because Plyr used vanilla-js didn't make it magically lighter, they had to handle that state/update logic somehow...
You're not loading the whole of React or whatever, tree-shaking has been a thing for ages.
Once compiled, there is no discernable difference between a WebComponent developed using a framework vs not build with one

**Comment by jimmywarting** [comment] 2025-07-14 18:24
I can agree that there is a reason to use framework at times, but there is also reason when you should not use them too.

**Comment by mrleblanc101** [comment] 2025-07-14 18:26
@jimmywarting And VidStack is EXTREMELY complex and modular, a PRIME exemple of when to use a framework...
There is a reason Plyr slowly died, maintainance and outside contribution were low, and brought breaking bugs.
You can still use it if you prefer.
