### ISSUE TITLE
Seek tooltip is not always an accurate indicator of seek on click

### ISSUE THREAD

**Issue by Moiahbabi** [sampotts/plyr#687] opened 2017-10-13 23:54 UTC
- [yes] Issue does not already exist
- [yes] Issue observed on https://plyr.io

### Expected behaviour 
while video paused, and seeking with mouse click , tooltip should show exact time as the video current time display.

### Actual behaviour
based on video duration, tooltip time and video current time are different by few second, in plyr.io 1s. see [img 01].

It seems to be due to the track thumb css properties. so I tried to give it a width of zero, with no borders
and it seems to give a correct time display for both tooltip and video current time. see [img 02].

### Environment

- Browser: (Chrome, Firefox, IE, Opera).
- Version:  
- Operating System: Windows 10
- Version: 1703

Players affected:
- [yes ] HTML5 Video
- [yes] HTML5 Audio
- [yes ] YouTube
- [yes] Vimeo

### Steps to reproduce 
- Load video
- pause video
- while paused, seek video by mouse click to a point further in the video.
- check tooltip time and current time. 

### Relevant links
[img 01]
![ezgif-5-b686d3fa15](https://user-images.githubusercontent.com/26636470/31553722-72a2668a-b04c-11e7-827f-d1f370a8b9cf.gif)

[img 02]
![2017-10-13 1](https://user-images.githubusercontent.com/26636470/31552667-35b26f02-b049-11e7-8317-0b635705b0aa.jpg)

**Comment by sampotts** [comment] 2017-11-06 12:12
This is a known issue and is super tricky - in the middle of the scrubber it's pretty accurate but as you go left or right of center the accuracy drops. It's worst at each extreme. The problem is the way the tooltip value is calculated is based on the mouse offset from left to right but the range doesn't quite work like that as the *edge* of the handle for the range input is only inline with the *edge* of the track rather than the center of the handle being in the *centre* of the *end* of the track.  I'll look into it but as I say, it's a tricky one to do.

**Comment by friday** [comment] 2018-05-26 15:43
Fixed in 3.3.8

**Closed by friday** 2018-05-26 15:43 UTC
Labels: Bug
