### ISSUE TITLE
Videos blink when displaying multiple on one page

### ISSUE THREAD

**Issue by oguilleux** [sampotts/plyr#973] opened 2018-05-23 12:33 UTC
### Expected behaviour
Videos do not blink

### Actual behaviour
Videos blink when user scrolls
### Environment

- Browser: Chrome
- Version: 66
- Operating System: Mac OSX High Sierra 
- Version: 10.13.4

### Steps to reproduce
- Open Chrome, Go on this link : https://goo.gl/RwNA2E, Scroll down and note that videos blink.

**Comment by friday** [comment] 2018-05-23 12:39
Can't reproduce (Chrome 66 on osx). Might be a memory things?

Does it happen if you remove Plyr and only use html5 video?

**Comment by oguilleux** [comment] 2018-05-23 12:48
Yes It happens also when I'm not using Plyr and only using html5 video.

So I assume it doesn't come from Plyr. 

You speak about "memory thing" do you have a lead on where I could search ?

**Comment by friday** [comment] 2018-05-23 13:19
Yeah. Plyr doesn't handle the actual low level playback (as in parsing the video, drawing each frame etc). That's all HTML5.

Not really, but you could try restarting chrome fresh (no tabs open) open an "Incognito Window" (since that disables addons unless you specifically set them up for incognito too) and open the page.

Closing since it's not really something we can fix or avoid. Good luck!

**Closed by friday** 2018-05-23 13:19 UTC
