### ISSUE TITLE
Full Screen Size

### ISSUE THREAD

**Issue by doodah1772** [sampotts/plyr#733] opened 2017-12-08 18:14 UTC
- [X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

I have added a max-height to all videos but when I go to full screen it carries this attribute with it. So I'm looking for a way to reset the max-height value on my video, then restore the max-height value once exiting full-screen mode.

I did try Issue #503 but it does not work, neither would it restore my original max-height value when exiting full-screen.

Code:
`<video controls poster="../../Video/vertical.jpg" style="height:500px" preload="none"><source src="../../Video/vertical.mp4" type="video/mp4"></video>`

Tried:

```
<script language="javascript" type="text/javascript">
    $("button[data-plyr=fullscreen]").click(function(){      
                setTimeout(function() {
                    $("video").css("height", "100%");
                }, 1000)
            });
}
</script>
```

- Browser: All

Players affected:
- [X] HTML5 Video
- [ ] HTML5 Audio
- [X] YouTube
- [X] Vimeo

### Steps to reproduce 
-

**Comment by friday** [comment] 2017-12-08 18:39
It's impossible to tell the problem by this description, but it seems like a duplicate of #503. Please rephrase and complete the description with relevant information or close it and go to #503 if it's the same problem.

**Comment by doodah1772** [comment] 2017-12-08 19:24
I edited my comment with a little more information.

**Comment by friday** [comment] 2017-12-08 21:41
Please try setting the size on a wrapper to the video element instead of directly to the video or to the wrapper created by plyr.

**Comment by doodah1772** [comment] 2017-12-08 21:46
Figured out a much easier solution:

.plyr--fullscreen-active video {
max-height: 100% !important
}
Thanks for the effort, friday...

**Closed** 2017-12-08 21:47 UTC
