### ISSUE TITLE
Tooltip time has broken positioning in IE11

### ISSUE THREAD

**Issue by denilsonc** [sampotts/plyr#808] opened 2018-03-14 18:02 UTC
Tooltip time not working in ie11/window 7

Português Brasil:
A Dica da ferramenta não funciona usando iframe no ie11, fiz testes no chrome, opera, firefox e não tive nenhum problema.
 Ao mover o mouse sobre a barra de progresso o pre view time fica totalmente a direta da barra mas o tempo continua normal.

Até então não sei de onde vem o problema, acho que o problema esta vindo de pageXOffset mas não tenho como verificar.

**Comment by friday** [comment] 2018-03-14 18:24
Please keep it in English (you seem to know enough English to use online translation and verify later).

**Comment by denilsonc** [comment] 2018-03-14 18:48
I think it's a bug!

when I enter full screen the browser read the progress bar with 6px wide.
http://www.christophercurrie.com/technology/2014/03/20/internet-explorer-11-fullscreen-bug.html

**Comment by sampotts** [comment] 2018-03-18 12:46
Translated:

> The tooltip does not work using iframe in ie11, I did tests in chrome, opera, firefox and had no problem.
> By moving the mouse over the progress bar the pre-view time is totally in the direct bar but the time remains normal.
> Until then I do not know where the problem comes from, I think the problem is coming from pageXOffset but I can not verify.

Will take a look.

**Comment by friday** [comment] 2018-04-05 00:52
I can't reproduce this.

**Comment by denilsonc** [comment] 2018-04-05 11:12
with full screen?

**Comment by friday** [comment] 2018-04-05 12:30
It works with or without fullscreen in my setup.

**Comment by friday** [comment] 2018-06-08 15:30
Closing, since this cannot be reproduced with the given instructions. Both the tooltip time (since #958) and position works in IE11, with or without fullscreen.

**Closed by friday** 2018-06-08 15:30 UTC
