### ISSUE TITLE
Settings menu is not showing up when clicked

### ISSUE THREAD

**Issue by eberc** [sampotts/plyr#1409] opened 2019-04-11 05:01 UTC
when i click on the settings icon, the whole video window goes up and settings don't show up, idk if it's a css or js bug

in fullscreen it's working well, can you help me?  thanks

**Comment by sampotts** [comment] 2019-04-11 05:03
Some info to help reproduce such as a codepen, jsfiddle, codesandbox will help. Currently I'm working blind. Sounds like external CSS crashing the party but I have no idea.

**Comment by eberc** [comment] 2019-04-11 05:18
my project is using a materialize css, i can't remember the version, i will check it today and run some tests later

**Comment by eberc** [comment] 2019-04-11 15:47
i think it's a conflict with materialize css/js https://codepen.io/eberc/pen/EJmrQp

**Comment by sampotts** [comment] 2019-04-25 02:22
Have you found out what the cause is yet? Not sure this is something we can fix our side.

**Comment by eberc** [comment] 2019-04-25 02:27
@sampotts I put the element outside the container and it worked

**Comment by sampotts** [comment] 2019-04-25 03:01
Great. So can we close this?

**Comment by eberc** [comment] 2019-04-25 03:03
@sampotts yeah, thanks!

**Closed** 2019-04-25 03:05 UTC
