### ISSUE TITLE
Is it possible to remove the black bar in YouTube player?

### ISSUE THREAD

**Issue by oggolc** [sampotts/plyr#2165] opened 2021-04-12 00:19 UTC
<img src="https://i.ibb.co/2dVjL6g/E100-D6-B4-E347-4-E6-E-B856-E7-A06-B86-EFC6.png">

https://plyr.io/#youtube

Like the black bar around the edge. Is it possible to remove it?
Is it a Youtube problem or maybe the video ratio?

Thank you

- Browser: Chrome
- Version: 3.6.4

**Comment by sampotts** [comment] 2021-04-18 07:50
This is fixed in 3.6.6 👍🏼

**Closed by sampotts** 2021-04-18 07:50 UTC

**Comment by anta199** [comment] 2021-04-30 10:11
This keeps happening in 3.6.7 I guess.

**Comment by sampotts** [comment] 2021-04-30 10:22
Can you send a screenshot? Make sure you've updated your CSS too. Check https://plyr.io. It was caused by the fact that the noembed API would often return weird sizes for videos like `200x113` for an obviously larger video, which calculated to an aspect ratio was _just_ shy of 16:9, hence the 1px black border. I wrote a function to round the aspect ratio to account for this margin of error.

**Comment by anta199** [comment] 2021-04-30 11:29
> Can you send a screenshot? Make sure you've updated your CSS too. Check https://plyr.io. It was caused by the fact that the noembed API would often return weird sizes for videos like `200x113` for an obviously larger video, which calculated to an aspect ratio was _just_ shy of 16:9, hence the 1px black border. I wrote a function to round the aspect ratio to account for this margin of error.

Screenshot: https://snipboard.io/T3hbS7.jpg
Here it can be noticed specially in the top of the wrapper.

I'm calling the 3.6.7 version via CDN:
https://cdn.plyr.io/3.6.7/plyr.css

Thanks for the great work!
