### ISSUE TITLE
Captions will only display in Brackets Live Preview; Nowhere else

### ISSUE THREAD

**Issue by kevinmahoney1995** [sampotts/plyr#732] opened 2017-12-07 16:15 UTC
- [x] Issue does not already exist

### Expected behaviour 
Captions to display across all browsers.

### Actual behaviour
Captions do not display at all, unless I am viewing the page in Brackets Live Preview.

### Environment
- Browser: Internet Explorer/Google Chrome/Firefox
- Version:  IE 11/Chrome 62.0.3202.94/Firefox 56
- Operating System: Microsoft Windows
- Version: 10 Pro

Players affected:
- [X ] HTML5 Video

### Steps to reproduce 
-Convert SRT file to VTT
-Reference VTT file in code
-Open web page from network drive web server in Brackets Live Preview **(Public does not have access to this link)**
-(Captions work)
-Open live page on the web in any browser on any computer 
-(Captions do not display)

![error](https://user-images.githubusercontent.com/34346798/33725273-b048748e-db3f-11e7-91d8-982479d0fd90.png)

Note that the browser on the left has Adblock Plus installed. I have tested this on browsers which do not have ABP installed and I still experience the issue.

**Comment by friday** [comment] 2017-12-07 16:32
I'm heavily using captions and haven't seen this in any browser.
Which Plyr version are you using?
If you inspect the caption element, does it not exist, or exists but is hidden, invisible, or off screen?

**Comment by kevinmahoney1995** [comment] 2017-12-07 16:51
Plyr v2.0.18 according to my changelog.

As for inspecting the element -- nothing is revealed on screen when I do this. Other things become highlighted to indicate their location on screen, but when I hover the cursor over the caption element <track kind="captions" label="English captions" src="video.vtt" srclang="en" default="" class=""> nothing on screen is highlighted. 

You'll have to forgive me, web design is not my primary function here nor is it my field of expertise, but I am trying as best I can to implement this player (as it is far superior to the outdated one we currently use.)

![plyrtest2](https://user-images.githubusercontent.com/34346798/33727035-dcc309c0-db44-11e7-8a46-247208c8f162.png)

**Comment by friday** [comment] 2017-12-07 17:12
Plyr doesn't use the original cue element for captions as it's terribly ugly and can't be styled properly.

This is what you should be looking for:

![screen shot 2017-12-07 at 18 07 42](https://user-images.githubusercontent.com/515120/33728088-982d948a-db79-11e7-872c-d6346b853c70.png)

Your plyr__captions element is empty, which it should only be if there aren't any caption at the time.

**Comment by kevinmahoney1995** [comment] 2017-12-07 17:35
How do I implement the .vtt file then? I was under the impression that this was all I needed to do. Works fine in the preview, but when viewing it on the web it falls apart.
![image](https://user-images.githubusercontent.com/34346798/33729224-fba159d6-db4a-11e7-94c0-6f014da50990.png)

**Comment by friday** [comment] 2017-12-07 17:43
I don't think the vtt or html is wrong if it this works in Brackets. I think you've probably disabled it (stored in localStorage) or used css somewhere that hides it.

Could you grab a screenshot from Brackets?

Also: Could you set up an example online (for example jsbin.com) with a minimal code to implement the subs.

**Comment by kevinmahoney1995** [comment] 2017-12-07 17:58
You're on to something with it being a problem with it being stored. But it is not stored in my local storage. It is indeed uploaded to the web server.

So, this is strange. I think I've figured out where the problem lies. No matter where I put this .vtt file, my browser can't open it if I navigate directly to it. The browser **can** open files which were stored _in that exact same folder_. But not .vtt files! I get a 404 error. It's as if the file does not exist.

**Comment by friday** [comment] 2017-12-07 19:11
That's not actually what I was referring to, so I guess I wasn't on to something after all ;)

Perhaps it's a typo then, or misconfigured server. If it's really a 404 error it shouldn't be mime-type related I think, but then it also shouldn't work in Brackets (or does Brackets use it's own server?)

If it's mime-type related, try setting mimetype to "text/vtt" for .vtt files (this should be done in the server conf).

**Comment by kevinmahoney1995** [comment] 2017-12-07 20:58
Brackets doesn't use its own server. 

I've double and triple checked my addresses and there's no typo. The file truly is in the folder, but it returns a 404 if you try to access it in your browser. Other files in this folder are accessible. 

This mime-type thing you're talking about, I'm unfamiliar with it and I am not an administrator for this server. I assume one would have to be an administrator to access the server config.

**Comment by friday** [comment] 2018-05-17 01:00
Closing since this I can't reproduce this and it hasn't been reported by anyone else.

**Closed by friday** 2018-05-17 01:00 UTC
Labels: Invalid
