### ISSUE TITLE
Play multiple video at certain time without autoplay

### ISSUE THREAD

**Issue by manlioma** [sampotts/plyr#906] opened 2018-04-17 21:04 UTC
### Expected behaviour
I want to play video from vimeo at certain time, but I don't want the autoplay

### Actual behaviour
One video starts

### Environment

- Browser: Chrome
- Version:  65.0.3325.181
- Operating System: Os Sierra
- Version: 10.13.4

### Steps to reproduce
- Hello I try to figure out with this code. I have different videos on same page with class=".plyr-big". Some videos are from Vimeo and starting at certain time. With this the video is going in autoplay and I have to stop it. What is wrong? Thank you here's the [codepen](https://stackoverflow.com/questions/49677217/add-function-to-each-item-of-jquery-map)

**Comment by friday** [comment] 2018-04-24 22:08
This is a duplicate of #876

**Comment by friday** [comment] 2018-05-26 13:09
Fixed in 3.3.8

**Closed by friday** 2018-05-26 13:09 UTC
