### ISSUE TITLE
Related videos section is shown in youtube version (although rel: 0 in playerVars)

### ISSUE THREAD

**Issue by MaHermes** [sampotts/plyr#1221] opened 2018-10-18 12:10 UTC
### Expected behaviour

The youtube player version of Plyr hides the related videos

### Actual behaviour

The youtube player version of Plyr displays the related videos if the video is paused

### Steps to reproduce

- Open https://plyr.io/#youtube
- Click play
- Click pause

=> related video section appears as an overlay

### Environment

- Browser: Firefox Quantum
- Version: 62.0.3

### Link to where the bug is happening

https://plyr.io/#youtube

**Comment by sampotts** [comment] 2018-10-18 12:16
Duplicate of #1222. Let’s take care of it in that one. I think it’s a YouTube issue though, sadly.

**Closed by sampotts** 2018-10-18 12:16 UTC
