### ISSUE TITLE
No option for repeat videos

### ISSUE THREAD

**Issue by ishanjm** [sampotts/plyr#748] opened 2018-01-04 07:28 UTC
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by sampotts** [comment] 2018-01-04 07:29
Duplicate of https://github.com/sampotts/plyr/issues/632 - have a search before raising issues 👍

**Closed by sampotts** 2018-01-04 07:29 UTC
