### ISSUE TITLE
controls icons not toggling using custom html

### ISSUE THREAD

**Issue by georgeejr** [sampotts/plyr#1062] opened 2018-06-22 08:53 UTC
I am using custom html for controls because i want to rearrange it but when i play the video or make it fullscreen the icons are not changing at all. Play icon should turn to pause and fullscreen should change to exit fullscreen icon. Just follow this docs https://github.com/sampotts/plyr/blob/master/controls.md

**Comment by georgeejr** [comment] 2018-06-22 09:32
v3.3.14

**Comment by friday** [comment] 2018-06-22 10:52
I'll copy that png and paste it into my code so I can test it ;)

**Comment by friday** [comment] 2018-06-25 11:11
No sorry, that was a joke (you can't copy a png image into your code). Please read our we have guidelines about replication that you should have seen: https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#replication

My guess is that your code was copied from Plyr before v3.3.13, and that the controls have changed since (they have in #1041, but I'm not sure exactly what changed), so try downgrading Plyr to 3.3.12 or upgrading your buttons by copying from the default button output of a newer Plyr version (or however you did it originally).

I'm not sure this fixes the problem.

**Comment by wizedesign** [comment] 2018-07-04 11:55
I copied the original code https://github.com/sampotts/plyr/blob/master/controls.md#example-1 and the same issues "controls icons not toggling".

https://codepen.io/anon/pen/JZVVWM

Is there any solution?

**Comment by jwjcmw** [comment] 2018-08-07 20:38
I'm just here to +1 this issue.  I've got a pen showing the issue with 3.3.23 here
https://codepen.io/jwjcmw/pen/mjzWRQ
as with @wizedesign above, I just copied in the controls example verbatim.

**Comment by jwjcmw** [comment] 2018-08-08 03:39
It looks like the issue is that when the standard controls are created, this property is added to each button:
```javascript
Object.defineProperty(button, 'pressed', {
  enumerable: true,
  get() {
    return hasClass(button, className);
  },
  set(pressed = false) {
    toggleClass(button, className, pressed);
  },
});
```
But that doesn't get done with the custom buttons.  I've got a hack in place in mine now to do this to my custom buttons right before the Edge redraw in the inject function.

**Comment by sampotts** [comment] 2018-08-13 13:52
I'll be deploying a fix for this shortly

**Closed** 2018-08-13 14:00 UTC
Labels: Replicated

**Comment by ndimatteo** [comment] 2018-08-13 19:47
Sigh. This still doesn't work. Now when rendering, this error comes up: `Object.defineProperty called on non-object`

Set this up exactly as you have it in the controls.md doc too:
`var player = new Plyr('.video-player', { controls: controls });`

**Comment by friday** [comment] 2018-08-13 19:49
@ndimatteo That's not very helpful. Create a new issue and follow the template.

**Comment by ndimatteo** [comment] 2018-08-13 20:38
@friday sorry, here's a more detailed issue about the problem: #1161

**Comment by sampotts** [comment] 2018-08-13 23:15
Sigh. I still didn't get a pull request. Don't worry though, you sit back.
