### ISSUE TITLE
Humongous captions on Vimeo

### ISSUE THREAD

**Issue by Antonio-Laguna** [sampotts/plyr#1205] opened 2018-10-08 06:07 UTC
### Expected behaviour

Captions should be normal instead of that big.

### Actual behaviour

They're huge.

![](https://media.sgff.io/sgff_r1eHetbDYb/2018-10-01/1538428458198/Screen_Shot_2018-09-28_at_4.12.22_PM.png)

### Environment

- Browser: Chrome
- Version: Latest
- Operating System: macOS
- Version: 3.4.3

### Explanation

We've unearthed an odd bug using plyr.

Now, we have this video: https://vimeo.com/210700694 which can be seen just fine. However, when embedded, the captions get somehow stretched a lot and enabling/disabling the captions via API doesn't disable them. They seem to be burned into the video so there's no way to get them out and it's a bit annoying.

We've discovered that disabling captions from within Vimeo page and then going back to our embed (without any further change) fixes the issue. Also disabling captions within the video setting fixes it.

We've prepared a little playground for you to see https://codepen.io/Belelros/pen/ZqbYpO if you open that on incognito and play the video on top (which is using plyr) you'll see the issue right away, around second 0:43. If you then, while playing click on the video below and disable the captions, you'll see the huge captions disappear.

Now. I've passed this to Vimeo and they said it wasn't them (though it seems them to me). However I did a quick test with the vimeo player on another Codepen and the issue wasn't there. https://codepen.io/Belelros/pen/xyRded

**Comment by friday** [comment] 2018-10-11 19:33
Duplicate of #877 

Unfortunately not such an odd bug.

**Closed by friday** 2018-10-11 19:33 UTC
