### ISSUE TITLE
Media controls layout messed up on qutebrowser

### ISSUE THREAD

**Issue by benwaffle** [sampotts/plyr#274] opened 2016-06-11 02:49 UTC
![screenshot from 2016-06-10 22-49-24](https://cloud.githubusercontent.com/assets/1713819/15982708/9c115dd0-2f5d-11e6-98ce-e4b62ff90f87.png)
![screenshot from 2016-06-10 22-49-27](https://cloud.githubusercontent.com/assets/1713819/15982710/9d4e33a8-2f5d-11e6-99c8-60552a364cdc.png)

**Comment by SamPotts** [comment] 2016-06-11 14:53
First time I've heard of it. Presume it doesn't support flex box? What's the market share ?

Sam

**Comment by benwaffle** [comment] 2016-06-11 18:01
slim to none? It uses QtWebkit though

**Comment by friday** [comment] 2018-05-30 19:06
I'm closing this since it's such a small browser that we don't officially support. It may already be fixed (both qutebrowser and Plyr have gone through two years of development since the issue), but if not, PR's are welcome.

**Closed by friday** 2018-05-30 19:06 UTC
Labels: Browser Issue

**Comment by The-Compiler** [comment] 2018-05-30 20:27
qutebrowser maintainer here - not sure why, but apparently I subscribed to this issue and forgot :laughing: 

I can confirm things look good nowadays, at least with the newer QtWebEngine backend which is based on Chromium.

**Comment by friday** [comment] 2018-05-30 20:42
Great to know, and thank you for the update!
