### ISSUE TITLE
External captions on Vimeo or YouTube

### ISSUE THREAD

**Issue by Hammin** [sampotts/plyr#521] opened 2017-02-26 18:44 UTC
Hi. Is it possible to add external captions when data type is youtube or vimeo?
Greetings. Thank you very much for offering Plyr.

Players affected:
- [x] YouTube
- [x] Vimeo

**Comment by gtaschuk** [comment] 2017-03-01 19:57
Seems to be a duplicate of #383

**Comment by sampotts** [comment] 2018-03-22 11:44
Will manage this in #383 . Vimeo captions are now supported as of v3 👍

**Closed by sampotts** 2018-03-22 11:44 UTC

**Comment by friday** [comment] 2018-07-07 18:20
I think there's been some confusion about this. Would recommend #1090 over #383 for further discussion.

**Comment by friday** [comment] 2018-07-07 18:48
Reopened since I think this is actually a "bigger" issue than YouTube caption support and need it's own space. It's also possible to fix this without adding YouTube support for captions, and supporting this may help to add support for YouTube captions (#1090).

Plyr could potentially handle captions for any provider (live streams not included) by supporting VTT files. Either by parsing them and triggering events similar to `cuechange`. Or, by creating a hidden  media element (audio perhaps) just for the captions and using the real `cuechange` - event of this element (this may not work with #1090).

Parsing VTT (and SRT) is relatively easy, but would add some complexity to the code. The more formats supported, the more complexity added, so I don't think this should be a goal.

Pros:
* Some providers may not support captions or getting captions using their SDK, or their Plyr lugins may not support it (like YouTube).
* Vimeo captions isn't currently safe to use #877
* Shaka Player create textTracks that don't work well with either Plyr or native HTML5 controls, and hls.js still may has issues with their captions making it unsafe. There is a flag for this (`captions.update`), but I think by adding a captions "override" that work for any provider (including HTML5 and streaming) we could make `captions.update` the *only* behavior and remove the option.

**Comment by rubenswieringa** [comment] 2018-12-12 20:40
@friday (or @sampotts) could you provide some insight into why external captions (captions that don’t already belong to the video) are [currently not supported](https://github.com/sampotts/plyr/blob/e8d2f23b81091fb60b70e9785bb18e33d897e77e/src/js/captions.js#L33) for Youtube videos?

I might be interested in implementing some of it if I understood the considerations for it not already being supported.

**Comment by friday** [comment] 2018-12-12 21:08
@rubenswieringa 

Normal HTML5 video implements [captions](https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video). Plyr uses this API to listen to events to show and hide cues (lines of text), while the actual HTML5 captions remain hidden (but not disabled, since we need the events).

Vimeo and YouTube may also be using this API for their implementations. Plyr can access approximately the same information via Vimeo's wrapper APIs, but not the raw original text track nodes, the original events or the original video elements.

In order to support for external subtitles you would probably have to fetch the caption, and parse it (since there's no HTML5 video to add it to as a track). Then you would need to listen to timeupdate and trigger the show/hide events when the cues should be shown.

I don't expect that to be very hard. [The parsing logic for VTT is very simple](https://github.com/sampotts/plyr/issues/771#issuecomment-366541669). Plyr doesn't have an API for adding captions that works for non-html-elements though.

**Comment by rubenswieringa** [comment] 2018-12-13 14:45
@friday 

Thank you for the (very concise) explanation, will be spending some time today looking into it and will keep you posted.

**Comment by friday** [comment] 2018-12-18 19:43
There's no rush though. Even if you did this super quickly, Sam doesn't have the time to keep up with the PR's and issues. You may want to ask him about this specifically before spending much time on it.
