### ISSUE TITLE
clickToPlay broken on touch devices

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#1162] opened 2018-08-13 21:20 UTC
### Expected behaviour
Tapping a paused or stopped video should start playing it when `clickToPlay` is enabled.

### Actual behaviour
On touch devices it does play initially when tapping, but after it's been paused and you tap it only plays briefly than pauses again. It seems like the `touchend` event is getting in the way. If you never release it works.

Probably related to the #968 fix?

### Environment
Chrome 68 (Android or Desktop with webtools touch-emulation)

### Link to where the bug is happening
https://plyr.io/

**Comment by sampotts** [comment] 2018-08-14 04:42
Damn it - that'd be my change. Fix one thing, break another 😂

**Comment by LittleHamster** [comment] 2018-08-25 16:00
@sampotts 
yes, I have the same issue, it is broken on the latest release
any timeline for fixing it? thanks

**Comment by jremi** [comment] 2018-08-25 21:08
Same issue here.... I might need to roll back to a different version. What is the last version where this issue was not happening?

**Comment by jremi** [comment] 2018-08-25 21:40
I ended up for now downgrading back to v3.3.23. Because it allows the control to fadeup when you tap the viewer. In the newer version it wont toggle play/pause on tap.

**Comment by jamesoflol** [comment] 2018-09-07 06:04
The issue is that video play() is bound to both `click` *and* `touchstart` (listeners.js:375). Naturally, the video starts playing on touchstart, and then a couple hundred milliseconds later the click event fires and pauses it.

So obviously we don't want both, but can someone with more experience please enlighten me to why we might want to involve the touchstart event at all? It's the equiv of firing on mousedown. `Click` is so nice and universal. Obviously click has a delay because it fires on mouseup.. but I consider this to be minor. `touchstart` also has a host of other issues. Primarily that someone who tries to scroll the page by swiping on the video itself will cause it to start playing (well, it would if the bug didn't cause it to immediately pause again afterwards! :p). Swiping over video is a pretty likely scenario on mobile of course, because video takes up most of the page.

So, obvious solution (and I have tested this) is to simply remove touchstart as an event trigger for play().

A side effect of fixing this, however, is that "First touch on touch devices will just show controls" (listeners.js:383) is no longer true. But was it ever true/working?? The reason for this appears to be two-fold. One, is that `toggleControls()` is fired by the `touchstart` event at line 291, and as such the controls are always showing again by the time our click event is fired. The fix here would seemingly be to also remove touchstart as an event trigger for this function. But I tried that, and found that there appears to be a race condition whereby which the container() elements.container listener fires immediately before the media() elements.container listener. To try to reorder those would put me way out of my depth with this codebase.

I'm putting in a PR to simply drop `touchstart` as an event trigger for the media play() event, as it's currently breaking things pretty badly.

**Comment by sampotts** [comment] 2018-09-25 13:46
This should be resolved in `v3.4.4`. Cheers all 👍

**Closed by sampotts** 2018-09-25 13:46 UTC

**Comment by tmk1991** [comment] 2019-06-04 13:53
clickToPlay doesn't seem to trigger video playing in Webkitview / ios.

**Comment by nolyboms** [comment] 2020-11-11 14:14
I am on iOS14 and when Vimeo-video starts to play the controls fade down and tapping/toiuching screen doesn't bring it back. The stay hidden until clip ends.

**Comment by prostoprojekt** [comment] 2020-12-17 16:54
I'm on iOS14.3 & w/ Plyr v.3.6.3 - same issue, I can start to play youtube vid's then the controls fade down and tapping/toiuching screen doesn't bring it back. The stay hidden until clip ends.

**Comment by kate-ivanova** [comment] 2021-02-05 10:37
I have the same issue(clickToPlay doesn't work on touch devices) even in mobile version via chrome dev tools. On iOS 14.4(Safari) too.

**Comment by kw005** [comment] 2023-05-10 10:29
I have the same issue with 3.7.8, even on chrome dev tools it does not work. Any quick fix or workaround?

**Comment by KRQPLY** [comment] 2024-02-26 15:56
Here's a quick workaround for anybody trying to fix this issue:

`this.player.on('click', (event) => {
  if (this.player.touch && event.target.tagName === 'VIDEO') {
    if (this.player.playing) {
      this.player.pause();
    } else {
      this.player.play();
    }
  }
});`

**Comment by samtigall** [comment] 2025-03-21 14:42
no workaround needed. 
you need to have 

```
"hideControls": false,
"clickToPlay":true, //default
```

in your plyr-config for it to work
